'use client';

import { Button, Checkbox } from '@heroui/react';
import { DataList, DataListItems } from '@/components/ui/data-list';
import { primaryActionButtonClassName } from '@/components/ui/action-button';
import { EmptyState, ErrorState, LoadingState } from '@/components/ui/states';
import { DeadlineBadge, StatusChip } from '@/components/ui/status';
import type { DeadlineResponse } from '@charitypilot/shared';

type DeadlineDueState = 'complete' | 'overdue' | 'due-soon' | 'upcoming';

const formatDate = (value: string) => {
  return new Date(value).toLocaleDateString('en-IE', {
    weekday: 'short',
    day: 'numeric',
    month: 'short',
    year: 'numeric',
  });
};

const daysBetweenTodayAnd = (value: string) => {
  const due = new Date(value);
  const now = new Date();
  const dueDay = new Date(due.getFullYear(), due.getMonth(), due.getDate());
  const today = new Date(now.getFullYear(), now.getMonth(), now.getDate());
  return Math.round((dueDay.getTime() - today.getTime()) / (1000 * 60 * 60 * 24));
};

const classifyDeadline = (deadline: DeadlineResponse) => {
  const daysUntil = daysBetweenTodayAnd(deadline.dueDate);
  let dueState: DeadlineDueState = 'upcoming';
  let badgeLabel = `${daysUntil} days left`;
  let priorityLabel = 'Scheduled';

  if (deadline.isComplete) {
    dueState = 'complete';
    badgeLabel = 'Complete';
    priorityLabel = 'Closed';
  } else if (daysUntil < 0) {
    dueState = 'overdue';
    badgeLabel = `${Math.abs(daysUntil)} days overdue`;
    priorityLabel = 'Board priority';
  } else if (daysUntil === 0) {
    dueState = 'due-soon';
    badgeLabel = 'Due today';
    priorityLabel = 'Due now';
  } else if (daysUntil <= 30) {
    dueState = 'due-soon';
    badgeLabel = `${daysUntil} days left`;
    priorityLabel = 'Due soon';
  }

  return {
    daysUntil,
    dueState,
    badgeLabel,
    priorityLabel,
    badgeTone: dueState,
    rowClass:
      dueState === 'overdue'
        ? 'border-rose-200 bg-rose-50/70 dark:border-rose-800 dark:bg-rose-950/30'
        : dueState === 'due-soon'
          ? 'border-amber-200 bg-amber-50/70 dark:border-amber-800 dark:bg-amber-950/30'
          : dueState === 'complete'
            ? 'border-gray-200 bg-gray-50 dark:border-gray-800 dark:bg-gray-900/70'
            : 'border-gray-200 bg-white dark:border-gray-800 dark:bg-gray-900',
  };
};

export function summarizeDeadlines(deadlines: DeadlineResponse[]) {
  return deadlines.reduce(
    (acc, deadline) => {
      const meta = classifyDeadline(deadline);
      if (!deadline.isComplete) acc.open += 1;
      if (meta.dueState === 'overdue') acc.overdue += 1;
      if (meta.dueState === 'due-soon') acc.dueSoon += 1;
      if (deadline.isAutoGenerated) acc.system += 1;
      return acc;
    },
    { open: 0, overdue: 0, dueSoon: 0, system: 0 },
  );
}

export function DeadlineListPanel({
  loading,
  loadError,
  sortedDeadlines,
  toggleDeadlineId,
  deletingDeadlineId,
  saving,
  onRetry,
  onAdd,
  onEdit,
  onDelete,
  onToggleComplete,
}: {
  loading: boolean;
  loadError: string;
  sortedDeadlines: DeadlineResponse[];
  toggleDeadlineId: string | null;
  deletingDeadlineId: string | null;
  saving: boolean;
  onRetry: () => void | Promise<void>;
  onAdd: () => void;
  onEdit: (deadline: DeadlineResponse) => void;
  onDelete: (deadline: DeadlineResponse) => void;
  onToggleComplete: (deadline: DeadlineResponse) => void | Promise<void>;
}) {
  return (
    <DataList
      title="Deadline list"
      description="Incomplete items appear first, then the nearest due date. Complete items stay visible for evidence history."
    >
      {loading ? (
        <LoadingState title="Loading deadlines" description="Checking your governance calendar." />
      ) : loadError && sortedDeadlines.length === 0 ? (
        <ErrorState
          title="Deadlines could not be loaded"
          description={loadError}
          action={(
            <Button size="sm" variant="flat" onPress={onRetry}>
              Try again
            </Button>
          )}
        />
      ) : sortedDeadlines.length === 0 ? (
        <EmptyState
          title="No deadlines yet"
          description="Auto-generated dates will appear once the organisation profile is set up. Add any board, funder, AGM, audit, or reporting dates you already know."
          action={(
            <Button size="sm" className={primaryActionButtonClassName} onPress={onAdd}>
              Add first deadline
            </Button>
          )}
        />
      ) : (
        <div className="space-y-3">
          {loadError ? (
            <ErrorState
              title="Some deadline data may be out of date"
              description={loadError}
              action={(
                <Button size="sm" variant="flat" onPress={onRetry}>
                  Refresh
                </Button>
              )}
            />
          ) : null}
          <div aria-live="polite" className="sr-only">
            {toggleDeadlineId ? 'Updating deadline status' : deletingDeadlineId ? 'Deleting deadline' : 'Deadline list ready'}
          </div>
          <DataListItems divided={false}>
            <div className="space-y-3 p-3">
              {sortedDeadlines.map((deadline) => {
                const meta = classifyDeadline(deadline);
                return (
                  <article key={deadline.id} className={`rounded-lg border p-4 ${meta.rowClass}`}>
                    <div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between">
                      <div className="flex min-w-0 gap-3">
                        <Checkbox
                          isSelected={deadline.isComplete}
                          aria-label={`Mark ${deadline.title} as ${deadline.isComplete ? 'incomplete' : 'complete'}`}
                          size="sm"
                          color="success"
                          isDisabled={
                            Boolean(toggleDeadlineId) ||
                            Boolean(deletingDeadlineId)
                          }
                          onValueChange={() => void onToggleComplete(deadline)}
                          className="mt-0.5 shrink-0"
                        />
                        <div className="min-w-0">
                          <div className="flex flex-wrap items-center gap-2">
                            <h3 className={`break-words text-sm font-semibold ${deadline.isComplete ? 'text-gray-500 line-through dark:text-gray-400' : 'text-gray-950 dark:text-gray-50'}`}>
                              {deadline.title}
                            </h3>
                            {deadline.isAutoGenerated ? (
                              <StatusChip tone="info">System deadline</StatusChip>
                            ) : (
                              <StatusChip tone="neutral">Custom</StatusChip>
                            )}
                            <StatusChip tone={meta.priorityLabel === 'Board priority' ? 'danger' : meta.priorityLabel === 'Due soon' || meta.priorityLabel === 'Due now' ? 'warning' : 'neutral'}>
                              {meta.priorityLabel}
                            </StatusChip>
                          </div>
                          {deadline.description ? (
                            <p className="mt-1 text-sm leading-6 text-gray-600 dark:text-gray-300">{deadline.description}</p>
                          ) : (
                            <p className="mt-1 text-sm leading-6 text-gray-500 dark:text-gray-400">No notes added.</p>
                          )}
                          <p className="mt-2 text-xs font-medium text-gray-600 dark:text-gray-300">
                            Due {formatDate(deadline.dueDate)}
                          </p>
                        </div>
                      </div>
                      <div className="flex shrink-0 flex-wrap items-center gap-2">
                        <DeadlineBadge tone={meta.badgeTone} ariaLabel={`Deadline status: ${meta.badgeLabel}`}>
                          {meta.badgeLabel}
                        </DeadlineBadge>
                        <Button
                          size="sm"
                          variant="flat"
                          onPress={() => onEdit(deadline)}
                          isDisabled={Boolean(toggleDeadlineId) || Boolean(deletingDeadlineId) || saving}
                        >
                          Edit
                        </Button>
                        <Button
                          size="sm"
                          variant="flat"
                          color="danger"
                          onPress={() => onDelete(deadline)}
                          isLoading={deletingDeadlineId === deadline.id}
                          isDisabled={
                            Boolean(toggleDeadlineId) ||
                            (Boolean(deletingDeadlineId) && deletingDeadlineId !== deadline.id) ||
                            saving
                          }
                        >
                          Delete
                        </Button>
                      </div>
                    </div>
                  </article>
                );
              })}
            </div>
          </DataListItems>
        </div>
      )}
    </DataList>
  );
}
