export enum OrganisationComplexity {
  SIMPLE = 'SIMPLE',
  COMPLEX = 'COMPLEX',
}

export enum LegalForm {
  CLG = 'CLG',
  TRUST = 'TRUST',
  UNINCORPORATED_ASSOCIATION = 'UNINCORPORATED_ASSOCIATION',
  OTHER = 'OTHER',
}

export enum CharitablePurpose {
  POVERTY_RELIEF = 'POVERTY_RELIEF',
  EDUCATION = 'EDUCATION',
  RELIGION = 'RELIGION',
  COMMUNITY_BENEFIT = 'COMMUNITY_BENEFIT',
}

export enum ComplianceStatus {
  COMPLIANT = 'COMPLIANT',
  WORKING_TOWARDS = 'WORKING_TOWARDS',
  NOT_STARTED = 'NOT_STARTED',
  NOT_APPLICABLE = 'NOT_APPLICABLE',
  EXPLAIN = 'EXPLAIN',
}

export enum ComplianceSignoffStatus {
  DRAFT = 'DRAFT',
  BOARD_REVIEW = 'BOARD_REVIEW',
  APPROVED = 'APPROVED',
}

export enum SubscriptionPlan {
  ESSENTIALS = 'ESSENTIALS',
  COMPLETE = 'COMPLETE',
}

export enum SubscriptionStatus {
  TRIALING = 'TRIALING',
  ACTIVE = 'ACTIVE',
  PAST_DUE = 'PAST_DUE',
  CANCELLED = 'CANCELLED',
  EXPIRED = 'EXPIRED',
}

export enum DocumentCategory {
  CONSTITUTION = 'CONSTITUTION',
  POLICY = 'POLICY',
  BOARD_MINUTES = 'BOARD_MINUTES',
  FINANCIAL_STATEMENT = 'FINANCIAL_STATEMENT',
  INSURANCE = 'INSURANCE',
  ANNUAL_REPORT = 'ANNUAL_REPORT',
  RISK_REGISTER = 'RISK_REGISTER',
  CODE_OF_CONDUCT = 'CODE_OF_CONDUCT',
  STRATEGIC_PLAN = 'STRATEGIC_PLAN',
  OTHER = 'OTHER',
}

export enum RegisterStatus {
  OPEN = 'OPEN',
  MONITORING = 'MONITORING',
  CLOSED = 'CLOSED',
}

export enum ConflictStatus {
  DECLARED = 'DECLARED',
  MANAGED = 'MANAGED',
  CLOSED = 'CLOSED',
}

export enum RiskCategory {
  GOVERNANCE = 'GOVERNANCE',
  FINANCIAL = 'FINANCIAL',
  OPERATIONAL = 'OPERATIONAL',
  LEGAL = 'LEGAL',
  SAFEGUARDING = 'SAFEGUARDING',
  REPUTATIONAL = 'REPUTATIONAL',
  FUNDRAISING = 'FUNDRAISING',
  DATA_PROTECTION = 'DATA_PROTECTION',
  OTHER = 'OTHER',
}

export enum AnnualReportFilingStatus {
  NOT_STARTED = 'NOT_STARTED',
  IN_PROGRESS = 'IN_PROGRESS',
  BOARD_APPROVED = 'BOARD_APPROVED',
  FILED = 'FILED',
}

export enum UserRole {
  OWNER = 'OWNER',
  ADMIN = 'ADMIN',
  MEMBER = 'MEMBER',
}

export enum DeadlineReminderStatus {
  SENT = 'SENT',
  SKIPPED = 'SKIPPED',
  FAILED = 'FAILED',
}
