export enum OrganisationComplexity {
  SIMPLE = "SIMPLE",
  COMPLEX = "COMPLEX",
}

export enum LegalForm {
  CLG = "CLG",
  TRUST = "TRUST",
  UNINCORPORATED_ASSOCIATION = "UNINCORPORATED_ASSOCIATION",
  OTHER = "OTHER",
}

export enum CharitablePurpose {
  POVERTY_RELIEF = "POVERTY_RELIEF",
  EDUCATION = "EDUCATION",
  RELIGION = "RELIGION",
  COMMUNITY_BENEFIT = "COMMUNITY_BENEFIT",
}

export enum ComplianceStatus {
  COMPLIANT = "COMPLIANT",
  WORKING_TOWARDS = "WORKING_TOWARDS",
  NOT_STARTED = "NOT_STARTED",
  NOT_APPLICABLE = "NOT_APPLICABLE",
  EXPLAIN = "EXPLAIN",
}

export enum ComplianceSignoffStatus {
  DRAFT = "DRAFT",
  BOARD_REVIEW = "BOARD_REVIEW",
  APPROVED = "APPROVED",
}

export enum SubscriptionPlan {
  ESSENTIALS = "ESSENTIALS",
  COMPLETE = "COMPLETE",
}

export enum SubscriptionStatus {
  TRIALING = "TRIALING",
  ACTIVE = "ACTIVE",
  PAST_DUE = "PAST_DUE",
  CANCELLED = "CANCELLED",
  EXPIRED = "EXPIRED",
}

export enum DocumentCategory {
  CONSTITUTION = "CONSTITUTION",
  POLICY = "POLICY",
  BOARD_MINUTES = "BOARD_MINUTES",
  FINANCIAL_STATEMENT = "FINANCIAL_STATEMENT",
  INSURANCE = "INSURANCE",
  ANNUAL_REPORT = "ANNUAL_REPORT",
  RISK_REGISTER = "RISK_REGISTER",
  CODE_OF_CONDUCT = "CODE_OF_CONDUCT",
  STRATEGIC_PLAN = "STRATEGIC_PLAN",
  OTHER = "OTHER",
}

export enum RegisterStatus {
  OPEN = "OPEN",
  MONITORING = "MONITORING",
  CLOSED = "CLOSED",
}

export enum ConflictStatus {
  DECLARED = "DECLARED",
  MANAGED = "MANAGED",
  CLOSED = "CLOSED",
}

export enum RiskCategory {
  GOVERNANCE = "GOVERNANCE",
  FINANCIAL = "FINANCIAL",
  OPERATIONAL = "OPERATIONAL",
  LEGAL = "LEGAL",
  SAFEGUARDING = "SAFEGUARDING",
  REPUTATIONAL = "REPUTATIONAL",
  FUNDRAISING = "FUNDRAISING",
  DATA_PROTECTION = "DATA_PROTECTION",
  OTHER = "OTHER",
}

export enum AnnualReportFilingStatus {
  NOT_STARTED = "NOT_STARTED",
  IN_PROGRESS = "IN_PROGRESS",
  BOARD_APPROVED = "BOARD_APPROVED",
  FILED = "FILED",
}

export enum UserRole {
  OWNER = "OWNER",
  ADMIN = "ADMIN",
  MEMBER = "MEMBER",
}

export enum UserLifecycleStatus {
  ACTIVE = "ACTIVE",
  SUSPENDED = "SUSPENDED",
  REMOVED = "REMOVED",
}

export enum AuthSessionRevocationReason {
  LOGOUT = "LOGOUT",
  ROTATED = "ROTATED",
  REFRESH_REUSE = "REFRESH_REUSE",
  PASSWORD_RESET = "PASSWORD_RESET",
  MEMBER_SUSPENDED = "MEMBER_SUSPENDED",
  MEMBER_REMOVED = "MEMBER_REMOVED",
  ADMIN_SESSION_REVOKED = "ADMIN_SESSION_REVOKED",
  ADMIN_ALL_SESSIONS_REVOKED = "ADMIN_ALL_SESSIONS_REVOKED",
  USER_SESSION_REVOKED = "USER_SESSION_REVOKED",
  USER_ALL_SESSIONS_REVOKED = "USER_ALL_SESSIONS_REVOKED",
  OWNERSHIP_CHANGED = "OWNERSHIP_CHANGED",
  ORGANISATION_INACTIVE = "ORGANISATION_INACTIVE",
  LEGACY_UNSPECIFIED = "LEGACY_UNSPECIFIED",
}

export enum DeadlineReminderStatus {
  RESERVED = "RESERVED",
  SENDING = "SENDING",
  SENT = "SENT",
  SKIPPED = "SKIPPED",
  FAILED = "FAILED",
  UNCERTAIN = "UNCERTAIN",
}

export enum DeadlineReminderReconciliationOutcome {
  ACCEPTED_CONFIRMED = "ACCEPTED_CONFIRMED",
  NOT_ACCEPTED_CONFIRMED = "NOT_ACCEPTED_CONFIRMED",
  UNKNOWN_ACKNOWLEDGED = "UNKNOWN_ACKNOWLEDGED",
}

export enum GeneratedDeadlineKind {
  CHARITY_ANNUAL_REPORT = "CHARITY_ANNUAL_REPORT",
  COMPANY_FINANCIAL_STATEMENTS = "COMPANY_FINANCIAL_STATEMENTS",
  COMPANY_ANNUAL_MEMBER_ACTION = "COMPANY_ANNUAL_MEMBER_ACTION",
  CRO_ANNUAL_RETURN = "CRO_ANNUAL_RETURN",
  LEGACY_UNVERIFIED = "LEGACY_UNVERIFIED",
}

export enum DeadlineSupersessionReason {
  INPUT_CHANGED = "INPUT_CHANGED",
  INPUT_REMOVED = "INPUT_REMOVED",
  RULE_CHANGED = "RULE_CHANGED",
  RECURRENCE_ADVANCED = "RECURRENCE_ADVANCED",
  LEGACY_MIGRATION = "LEGACY_MIGRATION",
}
