export enum OrganisationComplexity {
  SIMPLE = 'SIMPLE',
  COMPLEX = 'COMPLEX',
}

export enum LegalForm {
  CLG = 'CLG',
  TRUST = 'TRUST',
  UNINCORPORATED_ASSOCIATION = 'UNINCORPORATED_ASSOCIATION',
  OTHER = 'OTHER',
}

export enum CharitablePurpose {
  POVERTY_RELIEF = 'POVERTY_RELIEF',
  EDUCATION = 'EDUCATION',
  RELIGION = 'RELIGION',
  COMMUNITY_BENEFIT = 'COMMUNITY_BENEFIT',
}

export enum ComplianceStatus {
  COMPLIANT = 'COMPLIANT',
  WORKING_TOWARDS = 'WORKING_TOWARDS',
  NOT_STARTED = 'NOT_STARTED',
  NOT_APPLICABLE = 'NOT_APPLICABLE',
  EXPLAIN = 'EXPLAIN',
}

export enum SubscriptionPlan {
  ESSENTIALS = 'ESSENTIALS',
  COMPLETE = 'COMPLETE',
}

export enum SubscriptionStatus {
  TRIALING = 'TRIALING',
  ACTIVE = 'ACTIVE',
  PAST_DUE = 'PAST_DUE',
  CANCELLED = 'CANCELLED',
  EXPIRED = 'EXPIRED',
}

export enum DocumentCategory {
  CONSTITUTION = 'CONSTITUTION',
  POLICY = 'POLICY',
  BOARD_MINUTES = 'BOARD_MINUTES',
  FINANCIAL_STATEMENT = 'FINANCIAL_STATEMENT',
  INSURANCE = 'INSURANCE',
  ANNUAL_REPORT = 'ANNUAL_REPORT',
  RISK_REGISTER = 'RISK_REGISTER',
  CODE_OF_CONDUCT = 'CODE_OF_CONDUCT',
  STRATEGIC_PLAN = 'STRATEGIC_PLAN',
  OTHER = 'OTHER',
}

export enum UserRole {
  OWNER = 'OWNER',
  ADMIN = 'ADMIN',
  MEMBER = 'MEMBER',
}
