import assert from 'node:assert/strict';
import { test } from 'node:test';
import { deriveIrishGovernanceDeadlines } from '../services/deadline-calendar.js';
import { DeadlineService } from '../services/deadline.service.js';

const EXPECTED_UPDATED_AT = '2026-01-01T00:00:00.000Z';

type Call = { name: string; args: any };

function deadline(overrides: Record<string, unknown> = {}) {
  return {
    id: 'deadline-1',
    organisationId: 'org-1',
    title: 'Board review',
    description: null,
    dueDate: new Date('2026-06-30T00:00:00.000Z'),
    isAutoGenerated: false,
    scheduleVersion: 1,
    profileRuleKey: null,
    generatedKind: null,
    generatedKey: null,
    generationVersion: null,
    generationRuleVersion: null,
    generationFingerprint: null,
    generationSource: null,
    generationInputs: null,
    isComplete: false,
    completedDate: null,
    completionDateKnown: true,
    reminderDays: [30, 14, 7],
    supersededAt: null,
    supersededById: null,
    supersessionReason: null,
    archivedAt: null,
    createdAt: new Date('2026-01-01T00:00:00.000Z'),
    updatedAt: new Date('2026-01-01T00:00:00.000Z'),
    ...overrides,
  };
}

function organisation(overrides: Record<string, unknown> = {}) {
  return {
    financialYearEnd: null,
    legalForm: null,
    legalFormConfirmedAt: null,
    incorporationDate: null,
    memberCount: null,
    lastActualAgmDate: null,
    lastUnanimousAnnualMemberResolutionDate: null,
    croAnnualReturnDate: null,
    croAnnualReturnDateConfirmedAt: null,
    ...overrides,
  };
}

function buildService(options: {
  found?: ReturnType<typeof deadline> | null;
  listRows?: ReturnType<typeof deadline>[];
  generatedRows?: ReturnType<typeof deadline>[];
  reminderRows?: Array<Record<string, any>>;
  organisation?: ReturnType<typeof organisation>;
  updateManyCount?: number;
  updateError?: unknown;
  auditError?: unknown;
  /** Active rows in the Register of Members. 0 means the register is empty, so
   *  the calendar falls back to the hand-entered Organisation.memberCount. */
  activeMemberCount?: number;
} = {}) {
  const calls: Call[] = [];
  const found = options.found === undefined ? deadline() : options.found;
  const prisma = {
    $queryRaw: async (...args: unknown[]) => {
      calls.push({ name: '$queryRaw', args });
      return [{ id: 'org-1' }];
    },
    organisation: {
      findUniqueOrThrow: async (args: unknown) => {
        calls.push({ name: 'organisation.findUniqueOrThrow', args });
        return options.organisation ?? organisation();
      },
    },
    member: {
      count: async (args: unknown) => {
        calls.push({ name: 'member.count', args });
        return options.activeMemberCount ?? 0;
      },
    },
    deadline: {
      findMany: async (args: any) => {
        calls.push({ name: 'deadline.findMany', args });
        return args.where?.isAutoGenerated ? options.generatedRows ?? [] : options.listRows ?? [];
      },
      count: async (args: unknown) => {
        calls.push({ name: 'deadline.count', args });
        return options.listRows?.length ?? options.generatedRows?.length ?? 0;
      },
      findFirst: async (args: unknown) => {
        calls.push({ name: 'deadline.findFirst', args });
        return found;
      },
      findUniqueOrThrow: async (args: unknown) => {
        calls.push({ name: 'deadline.findUniqueOrThrow', args });
        return deadline({ ...found, isComplete: true, completedDate: new Date('2026-07-10T00:00:00.000Z') });
      },
      create: async (args: any) => {
        calls.push({ name: 'deadline.create', args });
        return deadline({ id: `created-${calls.length}`, ...args.data });
      },
      update: async (args: any) => {
        calls.push({ name: 'deadline.update', args });
        if (options.updateError) throw options.updateError;
        const definedData = Object.fromEntries(
          Object.entries(args.data).filter(([, value]) => value !== undefined),
        );
        return deadline({ id: args.where.id, ...found, ...definedData });
      },
      updateMany: async (args: any) => {
        calls.push({ name: 'deadline.updateMany', args });
        if (options.updateError) throw options.updateError;
        return { count: options.updateManyCount ?? 1 };
      },
    },
    deadlineReminderLog: {
      findMany: async (args: unknown) => {
        calls.push({ name: 'deadlineReminderLog.findMany', args });
        return options.reminderRows ?? [];
      },
      count: async (args: unknown) => {
        calls.push({ name: 'deadlineReminderLog.count', args });
        return options.reminderRows?.length ?? 0;
      },
    },
    deadlineChangeAudit: {
      create: async (args: unknown) => {
        calls.push({ name: 'deadlineChangeAudit.create', args });
        if (options.auditError) throw options.auditError;
        return {};
      },
    },
  };
  return { service: new DeadlineService({
    ...prisma,
    $transaction: async (callback: (tx: typeof prisma) => Promise<unknown>) => callback(prisma),
  } as never), calls };
}

test('list returns current non-archived rows with exact civil dates', async () => {
  const row = deadline();
  const { service, calls } = buildService({ listRows: [row] });
  const result = await service.list('org-1');

  assert.equal(result.data[0].dueDate, '2026-06-30');
  assert.deepEqual(calls.find((call) => call.name === 'deadline.findMany')?.args.where, {
    organisationId: 'org-1',
    supersededAt: null,
    archivedAt: null,
  });
});

test('history excludes open current occurrences and retains completed or superseded generated records', async () => {
  const historical = deadline({
    isAutoGenerated: true,
    isComplete: true,
    completedDate: new Date('2026-07-01T12:00:00.000Z'),
    generatedKind: 'CHARITY_ANNUAL_REPORT',
    generatedKey: 'irish.charity.annual-report',
    generationVersion: 1,
    generationRuleVersion: 1,
    generationFingerprint: 'a'.repeat(64),
  });
  const { service, calls } = buildService({ generatedRows: [historical] });

  const result = await service.history('org-1');

  assert.equal(result.data[0].completedDate, '2026-07-01T12:00:00.000Z');
  assert.deepEqual(calls.find((call) => call.name === 'deadline.findMany')?.args.where, {
    organisationId: 'org-1',
    isAutoGenerated: true,
    OR: [{ isComplete: true }, { supersededAt: { not: null } }],
  });
});

test('reminder history returns immutable occurrence snapshots instead of live edited deadline fields', async () => {
  const reservedAt = new Date('2026-06-01T09:00:00.000Z');
  const { service } = buildService({
    reminderRows: [{
      id: 'reminder-1',
      deadlineId: 'deadline-1',
      deadlineTitle: 'Annual report before later rename',
      deadlineDueDate: new Date('2026-06-30T00:00:00.000Z'),
      deadlineScheduleVersion: 3,
      deadlineSnapshotKnown: false,
      deliveryTimingKnown: false,
      legacyDeliveryStatus: 'FAILED',
      legacyRecordedAt: reservedAt,
      email: 'owner@example.org',
      reminderDays: 30,
      status: 'UNCERTAIN',
      error: 'Legacy provider outcome unknown',
      reservedAt,
      attemptedAt: null,
      providerRequestStartedAt: null,
      reconciliationOutcome: 'UNKNOWN_ACKNOWLEDGED',
      reconciledAt: new Date('2026-07-10T09:00:00.000Z'),
      sentAt: null,
    }],
  });

  const result = await service.reminderHistory('org-1');

  assert.equal(result.data[0].deadlineTitle, 'Annual report before later rename');
  assert.equal(result.data[0].deadlineDueDate, '2026-06-30');
  assert.equal(result.data[0].deadlineScheduleVersion, 3);
  assert.equal(result.data[0].deadlineContextKind, 'MIGRATION_TIME_CONTEXT');
  assert.equal(result.data[0].deadlineSnapshotKnown, false);
  assert.equal(result.data[0].deliveryTimingKnown, false);
  assert.equal(result.data[0].legacyDeliveryStatus, 'FAILED');
  assert.equal(result.data[0].legacyRecordedAt, reservedAt.toISOString());
  assert.equal(result.data[0].reservedAt, null);
  assert.equal(result.data[0].attemptedAt, null);
  assert.equal(result.data[0].providerRequestStartedAt, null);
  assert.equal(result.data[0].reconciliationOutcome, 'UNKNOWN_ACKNOWLEDGED');
  assert.equal(result.data[0].reconciledAt, '2026-07-10T09:00:00.000Z');
  assert.equal(result.data[0].sentAt, null);
});

test('create scopes a manual deadline, preserves stable profile rule identity, and defaults reminders', async () => {
  const { service, calls } = buildService();
  const result = await service.create('org-1', {
    title: 'Safeguarding review',
    dueDate: '2026-09-30',
    profileRuleKey: 'worksWithChildrenOrVulnerableAdults',
  } as never, 'actor-1');

  const data = calls.find((call) => call.name === 'deadline.create')?.args.data;
  assert.equal(data.organisationId, 'org-1');
  assert.equal(data.profileRuleKey, 'worksWithChildrenOrVulnerableAdults');
  assert.deepEqual(data.reminderDays, [30, 14, 7]);
  assert.equal(result.dueDate, '2026-09-30');
  const audit = calls.find((call) => call.name === 'deadlineChangeAudit.create')?.args.data;
  assert.equal(audit.organisationId, 'org-1');
  assert.equal(audit.deadlineId, result.id);
  assert.equal(audit.actorUserId, 'actor-1');
  assert.equal(audit.action, 'CREATE');
  assert.equal(audit.nextState, 'OPEN');
  assert.doesNotMatch(JSON.stringify(audit), /Safeguarding review/);
});

test('calendar changes append metadata-only state history and fail closed on audit failure', async () => {
  const { service, calls } = buildService();
  await service.update('org-1', 'deadline-1', {
    expectedUpdatedAt: EXPECTED_UPDATED_AT, title: 'PRIVATE_NEW_TITLE', isComplete: true,
  }, 'actor-1');
  await service.remove('org-1', 'deadline-1', EXPECTED_UPDATED_AT, 'actor-1');
  const events = calls.filter((call) => call.name === 'deadlineChangeAudit.create')
    .map((call) => call.args.data as Record<string, unknown>);
  assert.deepEqual(events.map((event) => [event.action, event.previousState, event.nextState]), [
    ['COMPLETE', 'OPEN', 'COMPLETE'], ['ARCHIVE', 'OPEN', 'ARCHIVED'],
  ]);
  assert.deepEqual(events[0].changedFields, ['completedDate', 'isComplete', 'title']);
  assert.equal(events[0].actorUserId, 'actor-1');
  assert.doesNotMatch(JSON.stringify(events), /PRIVATE_NEW_TITLE/);

  const failed = buildService({ auditError: new Error('audit unavailable') });
  await assert.rejects(() => failed.service.create('org-1', {
    title: 'PRIVATE_NEW_TITLE', dueDate: '2026-09-30',
  }, 'actor-1'), /audit unavailable/);
});

test('cross-tenant updates and deletes fail before mutation', async () => {
  const { service, calls } = buildService({ found: null });
  await assert.rejects(
    () => service.update('org-attacker', 'other-org-deadline', {
      expectedUpdatedAt: EXPECTED_UPDATED_AT,
      title: 'Hijacked',
    }, 'actor-1'),
    (error: unknown) => (error as { code?: string }).code === 'DEADLINE_NOT_FOUND',
  );
  await assert.rejects(
    () => service.remove('org-attacker', 'other-org-deadline', EXPECTED_UPDATED_AT, 'actor-1'),
    (error: unknown) => (error as { code?: string }).code === 'DEADLINE_NOT_FOUND',
  );
  assert.equal(calls.some((call) => call.name === 'deadline.updateMany'), false);
});

test('manual deadlines remain editable and delete becomes a history-preserving archive', async () => {
  const { service, calls } = buildService();
  await service.update('org-1', 'deadline-1', {
    expectedUpdatedAt: EXPECTED_UPDATED_AT,
    dueDate: '2026-07-31',
    isComplete: true,
  }, 'actor-1');
  await service.remove('org-1', 'deadline-1', EXPECTED_UPDATED_AT, 'actor-1');

  const updates = calls.filter((call) => call.name === 'deadline.updateMany');
  assert.equal(updates[0].args.data.dueDate.toISOString(), '2026-07-31T00:00:00.000Z');
  assert.equal(updates[0].args.data.isComplete, true);
  assert.ok(updates[0].args.data.completedDate instanceof Date);
  assert.equal(updates[0].args.data.completionDateKnown, true);
  assert.deepEqual(updates[0].args.data.scheduleVersion, { increment: 1 });
  assert.ok(updates[1].args.data.archivedAt instanceof Date);
});

test('deadline optimistic versions accept an equivalent offset instant for update and archive', async () => {
  const equivalentOffset = '2026-01-01T01:00:00.000+01:00';
  const { service, calls } = buildService();

  await service.update('org-1', 'deadline-1', {
    expectedUpdatedAt: equivalentOffset,
    title: 'Offset-safe edit',
  }, 'actor-1');
  await service.remove('org-1', 'deadline-1', equivalentOffset, 'actor-1');

  const writes = calls.filter((call) => call.name === 'deadline.updateMany');
  assert.equal(writes.length, 2);
  assert.equal(writes[0].args.where.updatedAt.toISOString(), EXPECTED_UPDATED_AT);
  assert.equal(writes[1].args.where.updatedAt.toISOString(), EXPECTED_UPDATED_AT);
});

test('manual reschedule and reopen advance reminder occurrence identity while copy-only edits do not', async () => {
  const completed = deadline({
    isComplete: true,
    completedDate: new Date('2026-06-20T00:00:00.000Z'),
    scheduleVersion: 4,
  });
  const first = buildService({ found: completed });
  await first.service.update('org-1', completed.id, {
    expectedUpdatedAt: EXPECTED_UPDATED_AT,
    isComplete: false,
  }, 'actor-1');
  const reopen = first.calls.find((call) => call.name === 'deadline.updateMany');
  assert.deepEqual(reopen?.args.data.scheduleVersion, { increment: 1 });
  assert.equal(reopen?.args.data.completedDate, null);

  const second = buildService({ found: deadline({ scheduleVersion: 4 }) });
  await second.service.update('org-1', 'deadline-1', {
    expectedUpdatedAt: EXPECTED_UPDATED_AT,
    title: 'Renamed board review',
  }, 'actor-1');
  const rename = second.calls.find((call) => call.name === 'deadline.updateMany');
  assert.equal(rename?.args.data.scheduleVersion, undefined);

  const third = buildService({ found: deadline({ scheduleVersion: 4 }) });
  await third.service.update('org-1', 'deadline-1', {
    expectedUpdatedAt: EXPECTED_UPDATED_AT,
    description: 'Copy-only clarification',
  }, 'actor-1');
  const description = third.calls.find((call) => call.name === 'deadline.updateMany');
  assert.equal(description?.args.data.scheduleVersion, undefined);

  const fourth = buildService({ found: deadline({ scheduleVersion: 4, reminderDays: [30, 14, 7] }) });
  await fourth.service.update('org-1', 'deadline-1', {
    expectedUpdatedAt: EXPECTED_UPDATED_AT,
    reminderDays: [30, 14, 7, 1],
  }, 'actor-1');
  const windows = fourth.calls.find((call) => call.name === 'deadline.updateMany');
  assert.equal(windows?.args.data.scheduleVersion, undefined);
});

test('reopening an older profile review returns a stable conflict when a newer occurrence exists', async () => {
  const older = deadline({
    isComplete: true,
    completedDate: new Date('2026-06-20T00:00:00.000Z'),
    profileRuleKey: 'worksWithChildrenOrVulnerableAdults',
  });
  const { service } = buildService({
    found: older,
    updateError: Object.assign(new Error('duplicate profile review'), { code: 'P2002' }),
  });

  await assert.rejects(
    () => service.update('org-1', older.id, { expectedUpdatedAt: EXPECTED_UPDATED_AT, isComplete: false }, 'actor-1'),
    (error: unknown) => (error as { code?: string }).code === 'PROFILE_REVIEW_ALREADY_SCHEDULED',
  );
});

test('generated deadlines reject edits, reopen, and delete but permit one atomic completion', async () => {
  const generated = deadline({
    isAutoGenerated: true,
    generatedKind: 'CHARITY_ANNUAL_REPORT',
    generatedKey: 'irish.charity.annual-report',
    generationVersion: 1,
    generationRuleVersion: 1,
    generationFingerprint: 'a'.repeat(64),
  });
  const { service, calls } = buildService({ found: generated });

  for (const action of [
    () => service.update('org-1', generated.id, { expectedUpdatedAt: EXPECTED_UPDATED_AT, title: 'Changed' }, 'actor-1'),
    () => service.update('org-1', generated.id, { expectedUpdatedAt: EXPECTED_UPDATED_AT, isComplete: false }, 'actor-1'),
    () => service.remove('org-1', generated.id, EXPECTED_UPDATED_AT, 'actor-1'),
  ]) {
    await assert.rejects(action, (error: unknown) =>
      (error as { code?: string }).code === 'GENERATED_DEADLINE_IMMUTABLE');
  }

  const completed = await service.update('org-1', generated.id, {
    expectedUpdatedAt: EXPECTED_UPDATED_AT,
    isComplete: true,
  }, 'actor-1');
  assert.equal(completed.isComplete, true);
  const atomic = calls.find((call) => call.name === 'deadline.updateMany');
  assert.deepEqual(atomic?.args.where, {
    id: generated.id,
    organisationId: 'org-1',
    archivedAt: null,
    supersededAt: null,
    isComplete: false,
    updatedAt: new Date(EXPECTED_UPDATED_AT),
  });
  assert.equal(atomic?.args.data.completionDateKnown, true);
});

test('manual completion preserves its original instant and rejects stale admin writes', async () => {
  const completedAt = new Date('2026-06-20T12:00:00.000Z');
  const completed = deadline({ isComplete: true, completedDate: completedAt });
  const idempotent = buildService({ found: completed });
  await idempotent.service.update('org-1', completed.id, {
    expectedUpdatedAt: EXPECTED_UPDATED_AT,
    isComplete: true,
  }, 'actor-1');
  const completionWrite = idempotent.calls.find((call) => call.name === 'deadline.updateMany');
  assert.equal(completionWrite?.args.data.completedDate, undefined);

  const stale = buildService({
    found: deadline({ updatedAt: new Date('2026-02-01T00:00:00.000Z') }),
  });
  await assert.rejects(
    () => stale.service.update('org-1', 'deadline-1', {
      expectedUpdatedAt: EXPECTED_UPDATED_AT,
      dueDate: '2026-08-31',
    }, 'actor-1'),
    (error: unknown) => (error as { code?: string }).code === 'DEADLINE_UPDATE_CONFLICT',
  );
  assert.equal(stale.calls.some((call) => call.name === 'deadline.updateMany'), false);
});

test('unchanged completed generated occurrence is never reopened or rewritten', async () => {
  const spec = deriveIrishGovernanceDeadlines({
    ...organisation({ financialYearEnd: '2025-08-31' }),
  } as never)[0];
  const current = deadline({
    isAutoGenerated: true,
    isComplete: true,
    completedDate: new Date('2026-06-01T00:00:00.000Z'),
    generatedKind: spec.kind,
    generatedKey: spec.key,
    generationVersion: 1,
    generationRuleVersion: spec.ruleVersion,
    generationFingerprint: spec.fingerprint,
    dueDate: new Date(`${spec.dueDate}T00:00:00.000Z`),
  });
  const { service, calls } = buildService({
    organisation: organisation({ financialYearEnd: new Date('2025-08-31T00:00:00.000Z') }),
    generatedRows: [current],
  });

  await service.reconcileGeneratedDeadlines('org-1', 'actor-1');
  assert.equal(calls.some((call) => call.name === 'deadline.update'), false);
  assert.equal(calls.some((call) => call.name === 'deadline.create'), false);
  assert.equal(calls.some((call) => call.name === 'deadlineChangeAudit.create'), false);
});

test('changed source inputs supersede history and create a new incomplete successor version', async () => {
  const current = deadline({
    isAutoGenerated: true,
    isComplete: true,
    completedDate: new Date('2026-06-01T00:00:00.000Z'),
    generatedKind: 'CHARITY_ANNUAL_REPORT',
    generatedKey: 'irish.charity.annual-report',
    generationVersion: 1,
    generationRuleVersion: 1,
    generationFingerprint: 'a'.repeat(64),
  });
  const { service, calls } = buildService({
    organisation: organisation({ financialYearEnd: new Date('2026-08-31T00:00:00.000Z') }),
    generatedRows: [current],
  });

  await service.reconcileGeneratedDeadlines('org-1', 'actor-1');
  const updates = calls.filter((call) => call.name === 'deadline.update');
  const create = calls.find((call) => call.name === 'deadline.create');
  assert.equal(updates[0].args.data.supersessionReason, 'RECURRENCE_ADVANCED');
  assert.equal(create?.args.data.generationVersion, 2);
  assert.equal(create?.args.data.isComplete, false);
  assert.equal(create?.args.data.completedDate, null);
  assert.equal(create?.args.data.dueDate.toISOString(), '2027-06-30T00:00:00.000Z');
  assert.equal(updates[1].args.data.supersededById, create?.args.data.id ?? `created-${calls.indexOf(create!) + 1}`);
  const audits = calls.filter((call) => call.name === 'deadlineChangeAudit.create').map((call) => call.args.data);
  assert.deepEqual(audits.map((audit) => audit.action), ['SUPERSEDE', 'GENERATE']);
  assert.ok(audits.every((audit) => audit.actorUserId === 'actor-1' && audit.organisationId === 'org-1'));
  assert.equal(audits[0].deadlineId, current.id);
  assert.equal(audits[1].deadlineId, create?.args.data.id ?? `created-${calls.indexOf(create!) + 1}`);
});

test('new generated deadlines retain an actor-bound action and reject failed audit writes', async () => {
  const options = { organisation: organisation({ financialYearEnd: new Date('2026-08-31T00:00:00.000Z') }) };
  const created = buildService(options);
  await created.service.reconcileGeneratedDeadlines('org-1', 'profile-editor');
  const generated = created.calls.filter((call) => call.name === 'deadline.create');
  const audits = created.calls.filter((call) => call.name === 'deadlineChangeAudit.create');
  assert.ok(generated.length > 0);
  assert.equal(audits.length, generated.length);
  assert.ok(audits.every((call) => call.args.data.action === 'GENERATE'
    && call.args.data.actorUserId === 'profile-editor'
    && call.args.data.previousState === null
    && call.args.data.nextState === 'OPEN'));

  const failed = buildService({ ...options, auditError: new Error('audit unavailable') });
  await assert.rejects(
    failed.service.reconcileGeneratedDeadlines('org-1', 'profile-editor'),
    /audit unavailable/,
  );
});

test('removed or unconfirmed inputs supersede the current generated row without deleting history', async () => {
  const current = deadline({
    isAutoGenerated: true,
    generatedKind: 'COMPANY_FINANCIAL_STATEMENTS',
    generatedKey: 'irish.company.financial-statements',
    generationVersion: 1,
    generationRuleVersion: 1,
    generationFingerprint: 'b'.repeat(64),
  });
  const { service, calls } = buildService({ generatedRows: [current] });

  await service.reconcileGeneratedDeadlines('org-1', 'actor-1');
  const update = calls.find((call) => call.name === 'deadline.update');
  assert.equal(update?.args.data.supersessionReason, 'INPUT_REMOVED');
  assert.ok(update?.args.data.supersededAt instanceof Date);
  assert.equal(calls.some((call) => call.name === 'deadline.create'), false);
  const audit = calls.find((call) => call.name === 'deadlineChangeAudit.create')?.args.data;
  assert.equal(audit.action, 'SUPERSEDE');
  assert.deepEqual(audit.changedFields, ['supersededAt', 'supersessionReason']);
});
