import test from 'node:test';
import assert from 'node:assert/strict';
import {
  acceptTeamInviteSchema,
  ComplianceStatus,
  createCheckoutSchema,
  createRiskRecordSchema,
  inviteTeamMemberSchema,
  refreshSchema,
  upsertAnnualReportReadinessSchema,
  upsertComplianceSignoffSchema,
} from '@charitypilot/shared';

process.env.JWT_SECRET = process.env.JWT_SECRET ?? 'governance-workflow-test-secret';
process.env.JWT_EXPIRY = process.env.JWT_EXPIRY ?? '1h';

test('risk register validation enforces 1-5 likelihood and impact scores', () => {
  const result = createRiskRecordSchema.safeParse({
    title: 'Late annual filing',
    category: 'GOVERNANCE',
    description: 'Financial statements could be approved too late for annual filing.',
    likelihood: 6,
    impact: 4,
    mitigation: 'Board timetable and finance lead assigned.',
  });

  assert.equal(result.success, false);
  if (result.success) assert.fail('Risk validation should have failed');
  assert.match(result.error.issues[0]?.path.join('.') ?? '', /likelihood/);
});

test('board approval sign-off requires meeting date, minute reference, and approver', () => {
  const result = upsertComplianceSignoffSchema.safeParse({
    reportingYear: 2026,
    status: 'APPROVED',
  });

  assert.equal(result.success, false);
  if (result.success) assert.fail('Approved sign-off without approval fields should fail');
  assert.deepEqual(
    result.error.issues.map((issue) => issue.path.join('.')).sort(),
    ['approvedByName', 'boardMeetingDate', 'minuteReference'],
  );
});

test('annual report readiness accepts the expected governance workflow fields', () => {
  const result = upsertAnnualReportReadinessSchema.safeParse({
    reportingYear: 2026,
    activitiesNarrative: 'Programmes delivered across the year.',
    publicBenefitStatement: 'Activities advanced the charity purpose for public benefit.',
    financialStatementsApproved: true,
    trusteeDetailsReviewed: true,
    filingStatus: 'BOARD_APPROVED',
    boardApprovalDate: '2026-09-15',
  });

  assert.equal(result.success, true);
});

test('team invites restrict assignable roles and enforce invited account password strength', () => {
  assert.equal(inviteTeamMemberSchema.safeParse({ email: 'person@example.org', role: 'OWNER' }).success, false);
  assert.equal(inviteTeamMemberSchema.safeParse({ email: 'person@example.org', role: 'ADMIN' }).success, true);
  assert.equal(
    acceptTeamInviteSchema.safeParse({
      token: 'abc',
      name: 'Invited Trustee',
      password: 'weak',
    }).success,
    false,
  );
});

test('billing checkout accepts only supported plan intervals', () => {
  assert.equal(createCheckoutSchema.safeParse({ plan: 'COMPLETE', interval: 'yearly' }).success, true);
  assert.equal(createCheckoutSchema.safeParse({ plan: 'COMPLETE', interval: 'weekly' }).success, false);
});

test('refresh requests can rely on the secure refresh cookie', () => {
  assert.equal(refreshSchema.safeParse({}).success, true);
  assert.equal(refreshSchema.safeParse({ refreshToken: '' }).success, false);
});

test('clearing organisation profile dates removes stale pending auto-generated deadlines', async () => {
  const { DeadlineService } = await import('../services/deadline.service.js');
  const deletedDeadlineFilters: unknown[] = [];
  let manualDeadlineTouched = false;

  const prisma = {
    organisation: {
      findUniqueOrThrow: async () => ({
        id: 'org-1',
        financialYearEnd: null,
        lastAgmDate: null,
      }),
    },
    deadline: {
      deleteMany: async (query: unknown) => {
        deletedDeadlineFilters.push(query);
        return { count: 1 };
      },
      findFirst: async () => {
        manualDeadlineTouched = true;
        return null;
      },
      create: async () => {
        manualDeadlineTouched = true;
        return {};
      },
      update: async () => {
        manualDeadlineTouched = true;
        return {};
      },
    },
  };
  const service = new DeadlineService(prisma as never);

  await service.generateAutoDeadlines('org-1');

  assert.deepEqual(deletedDeadlineFilters, [
    {
      where: {
        organisationId: 'org-1',
        isAutoGenerated: true,
        isComplete: false,
        OR: [
          { title: { startsWith: 'Annual Report filing deadline (' } },
          { title: 'AGM due date' },
        ],
      },
    },
  ]);
  assert.equal(manualDeadlineTouched, false);
});

test('Essentials compliance summaries include only core standards even for complex organisations', async () => {
  const { ComplianceService } = await import('../services/compliance.service.js');

  const coreStandard = {
    id: 'standard-core',
    principleId: 'principle-1',
    isCore: true,
    principle: { id: 'principle-1', number: 1, title: 'Advancing charitable purpose' },
  };
  const additionalStandard = {
    id: 'standard-additional',
    principleId: 'principle-1',
    isCore: false,
    principle: { id: 'principle-1', number: 1, title: 'Advancing charitable purpose' },
  };
  const prisma = {
    organisation: {
      findUniqueOrThrow: async () => ({ id: 'org-1', complexity: 'COMPLEX' }),
    },
    subscription: {
      findUnique: async () => ({ plan: 'ESSENTIALS' }),
    },
    governanceStandard: {
      findMany: async (query: { where?: { isCore?: boolean } }) =>
        query.where?.isCore ? [coreStandard] : [coreStandard, additionalStandard],
    },
    complianceRecord: {
      findMany: async () => [
        { standardId: 'standard-core', status: 'COMPLIANT' },
        { standardId: 'standard-additional', status: 'COMPLIANT' },
      ],
    },
  };
  const service = new ComplianceService(prisma as never);

  const summary = await service.getSummary('org-1', 2026);

  assert.equal(summary.totalApplicable, 1);
  assert.equal(summary.compliant, 1);
  assert.equal(summary.percentComplete, 100);
});

test('Essentials recent activity excludes additional-standard compliance records', async () => {
  const { ActivityService } = await import('../services/activity.service.js');
  const coreRecord = {
    id: 'record-core',
    status: 'COMPLIANT',
    updatedAt: new Date('2026-01-02T10:00:00.000Z'),
    standard: { code: '1.1' },
    updatedBy: { id: 'user-1', name: 'Trustee One' },
  };
  const additionalRecord = {
    id: 'record-additional',
    status: 'COMPLIANT',
    updatedAt: new Date('2026-01-03T10:00:00.000Z'),
    standard: { code: '1.A' },
    updatedBy: { id: 'user-2', name: 'Trustee Two' },
  };
  const prisma = {
    organisation: {
      findUniqueOrThrow: async () => ({ id: 'org-1', complexity: 'COMPLEX' }),
    },
    subscription: {
      findUnique: async () => ({ plan: 'ESSENTIALS' }),
    },
    complianceRecord: {
      findMany: async (query: { where?: { standard?: { isCore?: boolean } } }) =>
        query.where?.standard?.isCore ? [coreRecord] : [coreRecord, additionalRecord],
    },
    document: { findMany: async () => [] },
    boardMember: { findMany: async () => [] },
    deadline: { findMany: async () => [] },
  };
  const service = new ActivityService(prisma as never);

  const activity = await service.getRecentActivity('org-1', 10);

  assert.deepEqual(
    activity.map((item) => item.description),
    ['Marked standard 1.1 as compliant'],
  );
});

test('Essentials document metadata excludes additional-standard links', async () => {
  const { DocumentService } = await import('../services/document.service.js');
  const documentRecord = {
    id: 'doc-1',
    organisationId: 'org-1',
    name: 'Evidence pack',
    description: null,
    category: 'POLICY',
    fileSize: 1024,
    mimeType: 'application/pdf',
    version: 1,
    owner: null,
    approvedDate: null,
    nextReviewDate: null,
    boardMinuteReference: null,
    uploadedById: 'user-1',
    createdAt: new Date('2026-01-04T10:00:00.000Z'),
    updatedAt: new Date('2026-01-04T10:00:00.000Z'),
  };
  const standardLinks = [
    { standardId: 'standard-core', standard: { id: 'standard-core', code: '1.1' } },
    { standardId: 'standard-additional', standard: { id: 'standard-additional', code: '1.A' } },
  ];
  const prisma = {
    organisation: {
      findUniqueOrThrow: async () => ({ id: 'org-1', complexity: 'COMPLEX' }),
    },
    subscription: {
      findUnique: async () => ({ plan: 'ESSENTIALS' }),
    },
    document: {
      findMany: async (query: { include?: { standardLinks?: { where?: { standard?: { isCore?: boolean } } } } }) => [
        {
          ...documentRecord,
          standardLinks: query.include?.standardLinks?.where?.standard?.isCore
            ? [standardLinks[0]]
            : standardLinks,
        },
      ],
      count: async () => 1,
    },
  };
  const service = new DocumentService(prisma as never);

  const documents = await service.list('org-1');

  assert.deepEqual(documents.data[0]?.standardLinks, [
    { standardId: 'standard-core', standardCode: '1.1' },
  ]);
});

test('Essentials organisations cannot write compliance records for additional standards', async () => {
  const { ComplianceService } = await import('../services/compliance.service.js');
  const { AppError } = await import('../utils/errors.js');
  let upsertCalled = false;
  const prisma = {
    organisation: {
      findUniqueOrThrow: async () => ({ id: 'org-1', complexity: 'COMPLEX' }),
    },
    subscription: {
      findUnique: async () => ({ plan: 'ESSENTIALS' }),
    },
    governanceStandard: {
      findUnique: async () => ({ id: 'standard-additional', isCore: false }),
    },
    complianceRecord: {
      upsert: async () => {
        upsertCalled = true;
        return {};
      },
    },
  };
  const service = new ComplianceService(prisma as never);

  await assert.rejects(
    () =>
      service.upsertRecord('org-1', 'standard-additional', 'user-1', {
        reportingYear: 2026,
        status: ComplianceStatus.COMPLIANT,
        actionTaken: 'Additional standard evidence',
      }),
    (error: unknown) =>
      error instanceof AppError &&
      error.statusCode === 403 &&
      error.code === 'COMPLIANCE_STANDARD_NOT_INCLUDED_IN_PLAN',
  );
  assert.equal(upsertCalled, false);
});

test('Essentials organisations cannot access Complete-only governance register endpoints', async () => {
  const [{ default: Fastify }, { governanceRegisterRoutes }, { signAccessToken }] = await Promise.all([
    import('fastify'),
    import('../routes/governance-registers/index.js'),
    import('../utils/jwt.js'),
  ]);

  let registerSummaryRead = false;
  const app = Fastify({ logger: false });
  app.decorate('prisma', {
    authSession: {
      findFirst: async () => ({ id: 'session-1' }),
    },
    user: {
      findUnique: async () => ({
        id: 'user-1',
        organisationId: 'org-1',
        role: 'OWNER',
        emailVerified: true,
      }),
    },
    subscription: {
      findUnique: async () => ({ status: 'ACTIVE', trialEndsAt: null, plan: 'ESSENTIALS' }),
    },
    conflictRecord: {
      count: async () => {
        registerSummaryRead = true;
        return 0;
      },
    },
    riskRecord: { count: async () => 0 },
    complaintRecord: { count: async () => 0 },
    fundraisingRecord: { count: async () => 0 },
    annualReportReadiness: { findUnique: async () => null },
    financialControlReview: { findUnique: async () => null },
  } as never);
  await app.register(governanceRegisterRoutes, { prefix: '/governance-registers' });

  try {
    const token = signAccessToken({
      userId: 'user-1',
      organisationId: 'org-1',
      role: 'OWNER',
      sessionId: 'session-1',
    });
    const response = await app.inject({
      method: 'GET',
      url: '/governance-registers/summary?year=2026',
      headers: { authorization: `Bearer ${token}` },
    });

    assert.equal(response.statusCode, 403);
    assert.equal(response.json().code, 'PLAN_FEATURE_UNAVAILABLE');
    assert.equal(registerSummaryRead, false);
  } finally {
    await app.close();
  }
});
