import type { FastifyInstance } from 'fastify';
import { ComplianceService } from '../../services/compliance.service.js';
import { authGuard } from '../../middleware/auth.js';
import { subscriptionGuard } from '../../middleware/subscription.js';
import { complianceQuerySchema } from '@charitypilot/shared';
import { handleError } from '../../utils/errors.js';
import { ZodError } from 'zod';

export async function exportRoutes(app: FastifyInstance) {
  const complianceService = new ComplianceService(app.prisma);

  app.addHook('onRequest', authGuard);
  app.addHook('onRequest', subscriptionGuard);

  // GET /compliance-record?year=2026&format=pdf
  app.get('/compliance-record', async (request, reply) => {
    try {
      const { year } = complianceQuerySchema.parse(request.query);
      const org = await app.prisma.organisation.findUniqueOrThrow({
        where: { id: request.user.organisationId },
      });

      const principles = await complianceService.getAllPrinciplesWithStandards();
      const records = await complianceService.getRecords(request.user.organisationId, year);
      const recordMap = new Map(records.map((r) => [r.standardId, r]));

      // Build HTML for PDF generation
      const html = buildComplianceReportHtml(org, principles, recordMap, year);

      // For MVP, return HTML that can be printed to PDF from browser
      // TODO: Use puppeteer or @react-pdf/renderer for server-side PDF generation
      reply.header('Content-Type', 'text/html');
      return html;
    } catch (err) {
      if (err instanceof ZodError) {
        return reply.status(400).send({ error: 'Validation failed', code: 'VALIDATION_ERROR', details: err.errors });
      }
      handleError(reply, err);
    }
  });
}

function buildComplianceReportHtml(
  org: { name: string; rcnNumber: string | null },
  principles: Array<{
    number: number;
    title: string;
    standards: Array<{ id: string; code: string; title: string; isCore: boolean }>;
  }>,
  recordMap: Map<string, { status: string; actionTaken: string | null; evidence: string | null; explanationIfNA: string | null }>,
  year: number,
): string {
  const standardRows = principles
    .map(
      (p) => `
      <h2>Principle ${p.number}: ${p.title}</h2>
      <table>
        <thead>
          <tr>
            <th>Standard</th>
            <th>Type</th>
            <th>Status</th>
            <th>Actions Taken</th>
            <th>Evidence</th>
          </tr>
        </thead>
        <tbody>
          ${p.standards
            .map((s) => {
              const r = recordMap.get(s.id);
              return `
              <tr>
                <td><strong>${s.code}</strong> ${escapeHtml(s.title)}</td>
                <td>${s.isCore ? 'Core' : 'Additional'}</td>
                <td>${r?.status?.replace(/_/g, ' ') ?? 'NOT STARTED'}</td>
                <td>${escapeHtml(r?.actionTaken ?? '')}</td>
                <td>${escapeHtml(r?.evidence ?? '')}${r?.explanationIfNA ? '<br><em>Explanation: ' + escapeHtml(r.explanationIfNA) + '</em>' : ''}</td>
              </tr>`;
            })
            .join('')}
        </tbody>
      </table>`,
    )
    .join('');

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Compliance Record Form — ${escapeHtml(org.name)} — ${year}</title>
  <style>
    body { font-family: 'Plus Jakarta Sans', Arial, sans-serif; max-width: 1100px; margin: 0 auto; padding: 40px 20px; color: #1a1a1a; }
    h1 { color: #0D7377; border-bottom: 3px solid #0D7377; padding-bottom: 8px; }
    h2 { color: #0D7377; margin-top: 32px; }
    table { width: 100%; border-collapse: collapse; margin-bottom: 24px; font-size: 13px; }
    th, td { border: 1px solid #d1d5db; padding: 8px 10px; text-align: left; vertical-align: top; }
    th { background-color: #f0fdfa; font-weight: 600; }
    .header-info { margin-bottom: 32px; }
    .header-info p { margin: 4px 0; }
    @media print { body { padding: 0; } h1 { font-size: 20px; } table { font-size: 11px; } }
  </style>
</head>
<body>
  <h1>Charities Governance Code — Compliance Record Form</h1>
  <div class="header-info">
    <p><strong>Charity Name:</strong> ${escapeHtml(org.name)}</p>
    <p><strong>Registered Charity Number:</strong> ${escapeHtml(org.rcnNumber ?? 'N/A')}</p>
    <p><strong>Reporting Year:</strong> ${year}</p>
    <p><strong>Date Generated:</strong> ${new Date().toLocaleDateString('en-IE')}</p>
  </div>
  ${standardRows}
  <div style="margin-top: 48px; border-top: 2px solid #0D7377; padding-top: 16px;">
    <p><strong>Approved at Board Meeting on:</strong> ____________________</p>
    <p><strong>Signed by Chairperson:</strong> ____________________</p>
    <p><strong>Date:</strong> ____________________</p>
  </div>
  <footer style="margin-top: 32px; font-size: 11px; color: #6b7280;">
    Generated by CharityPilot.ie — Charity governance made simple.
  </footer>
</body>
</html>`;
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}
