import type { PrismaClient } from '@prisma/client';
import type { CreateDeadlineRequest, UpdateDeadlineRequest } from '@charitypilot/shared';
import { AppError } from '../utils/errors.js';

export class DeadlineService {
  constructor(private prisma: PrismaClient) {}

  async list(organisationId: string) {
    return this.prisma.deadline.findMany({
      where: { organisationId },
      orderBy: { dueDate: 'asc' },
    });
  }

  async create(organisationId: string, data: CreateDeadlineRequest) {
    return this.prisma.deadline.create({
      data: {
        organisationId,
        title: data.title,
        description: data.description,
        dueDate: new Date(data.dueDate),
        reminderDays: data.reminderDays ?? [30, 14, 7],
      },
    });
  }

  async update(organisationId: string, id: string, data: UpdateDeadlineRequest) {
    const deadline = await this.prisma.deadline.findFirst({
      where: { id, organisationId },
    });

    if (!deadline) {
      throw new AppError(404, 'DEADLINE_NOT_FOUND', 'Deadline not found');
    }

    return this.prisma.deadline.update({
      where: { id },
      data: {
        title: data.title,
        description: data.description,
        dueDate: data.dueDate ? new Date(data.dueDate) : undefined,
        isComplete: data.isComplete,
        completedDate: data.isComplete ? new Date() : data.isComplete === false ? null : undefined,
        reminderDays: data.reminderDays,
      },
    });
  }

  async remove(organisationId: string, id: string) {
    const deadline = await this.prisma.deadline.findFirst({
      where: { id, organisationId },
    });

    if (!deadline) {
      throw new AppError(404, 'DEADLINE_NOT_FOUND', 'Deadline not found');
    }

    await this.prisma.deadline.delete({ where: { id } });
  }

  async generateAutoDeadlines(organisationId: string) {
    const org = await this.prisma.organisation.findUniqueOrThrow({
      where: { id: organisationId },
    });

    const deadlines: { title: string; dueDate: Date }[] = [];

    // Annual Report filing deadline: financial year end + 10 months
    if (org.financialYearEnd) {
      const fyEnd = new Date(org.financialYearEnd);
      const currentYear = new Date().getFullYear();
      const filingDeadline = new Date(currentYear, fyEnd.getMonth() + 10, fyEnd.getDate());
      deadlines.push({
        title: `Annual Report filing deadline (${currentYear})`,
        dueDate: filingDeadline,
      });
    }

    // AGM due date: within 15 months of previous AGM
    if (org.lastAgmDate) {
      const lastAgm = new Date(org.lastAgmDate);
      const agmDue = new Date(lastAgm);
      agmDue.setMonth(agmDue.getMonth() + 15);
      deadlines.push({
        title: 'AGM due date',
        dueDate: agmDue,
      });
    }

    for (const d of deadlines) {
      await this.prisma.deadline.upsert({
        where: {
          id: `auto-${organisationId}-${d.title}`,
        },
        create: {
          organisationId,
          title: d.title,
          dueDate: d.dueDate,
          isAutoGenerated: true,
          reminderDays: [30, 14, 7],
        },
        update: {
          dueDate: d.dueDate,
        },
      }).catch(() => {
        // Auto-deadline may already exist with different id; create if not
        return this.prisma.deadline.create({
          data: {
            organisationId,
            title: d.title,
            dueDate: d.dueDate,
            isAutoGenerated: true,
            reminderDays: [30, 14, 7],
          },
        });
      });
    }
  }
}
