import { Prisma, type Deadline, type PrismaClient } from '@prisma/client';
import type { CreateDeadlineRequest, UpdateDeadlineRequest } from '@charitypilot/shared';
import { AppError } from '../utils/errors.js';
import {
  civilDateFromPrisma,
  nullableCivilDateFromPrisma,
  prismaDateFromCivil,
} from '../utils/civil-date.js';
import {
  deriveIrishGovernanceDeadlines,
  type GeneratedDeadlineSpec,
} from './deadline-calendar.js';

type DeadlinePrisma = Pick<
  Prisma.TransactionClient,
  'deadline' | 'deadlineReminderLog' | 'deadlineChangeAudit' | 'organisation' | 'member' | '$queryRaw'
>;

type DeadlineWithGeneration = Deadline & {
  profileRuleKey?: string | null;
};

export const memberDeadlineSelect = {
  id: true, organisationId: true, title: true, dueDate: true,
  scheduleVersion: true, isAutoGenerated: true, generatedKind: true,
  generationVersion: true, generationRuleVersion: true,
  isComplete: true, completedDate: true, completionDateKnown: true,
  reminderDays: true, supersededAt: true, supersessionReason: true,
  archivedAt: true, createdAt: true, updatedAt: true,
} as const satisfies Prisma.DeadlineSelect;

type MemberDeadlineSource = Prisma.DeadlineGetPayload<{ select: typeof memberDeadlineSelect }>;

// Older calculated rows were marked LEGACY_UNVERIFIED during migration and
// retain their old title. A Member may only see deadlines from current rules.
export const MEMBER_DEADLINE_FILTER = {
  isAutoGenerated: true,
  generatedKind: { not: 'LEGACY_UNVERIFIED' as const },
};

function isUniqueConstraintError(error: unknown) {
  return Boolean(error && typeof error === 'object' && (error as { code?: unknown }).code === 'P2002');
}

export function publicDeadline(deadline: DeadlineWithGeneration) {
  return {
    ...deadline,
    dueDate: civilDateFromPrisma(deadline.dueDate),
    completedDate: deadline.completedDate?.toISOString() ?? null,
    supersededAt: deadline.supersededAt?.toISOString() ?? null,
    archivedAt: deadline.archivedAt?.toISOString() ?? null,
    createdAt: deadline.createdAt.toISOString(),
    updatedAt: deadline.updatedAt.toISOString(),
  };
}

export function publicMemberDeadline(deadline: MemberDeadlineSource) {
  // The query selects only the fields below. The explicit response projection
  // also keeps private snapshots out if a future caller passes a wider row.
  return {
    id: deadline.id,
    organisationId: deadline.organisationId,
    title: deadline.title,
    description: null,
    dueDate: civilDateFromPrisma(deadline.dueDate),
    scheduleVersion: deadline.scheduleVersion,
    isAutoGenerated: deadline.isAutoGenerated,
    generatedKind: deadline.generatedKind,
    generatedKey: null,
    generationVersion: deadline.generationVersion,
    generationRuleVersion: deadline.generationRuleVersion,
    generationFingerprint: null,
    generationSource: null,
    generationInputs: null,
    profileRuleKey: null,
    isComplete: deadline.isComplete,
    completedDate: deadline.completedDate?.toISOString() ?? null,
    completionDateKnown: deadline.completionDateKnown,
    reminderDays: deadline.reminderDays,
    supersededAt: deadline.supersededAt?.toISOString() ?? null,
    supersededById: null,
    supersessionReason: deadline.supersessionReason,
    archivedAt: deadline.archivedAt?.toISOString() ?? null,
    createdAt: deadline.createdAt.toISOString(),
    updatedAt: deadline.updatedAt.toISOString(),
  };
}

function pageBounds(page: number, pageSize: number) {
  const safePage = Math.max(1, page);
  const safePageSize = Math.min(100, Math.max(1, pageSize));
  return { page: safePage, pageSize: safePageSize, skip: (safePage - 1) * safePageSize };
}

function normalizeReminderDays(values: number[]) {
  return [...new Set(values)].sort((left, right) => right - left);
}

function generationData(organisationId: string, spec: GeneratedDeadlineSpec, version: number) {
  return {
    organisationId,
    title: spec.title,
    description: spec.description,
    dueDate: prismaDateFromCivil(spec.dueDate),
    isAutoGenerated: true,
    generatedKind: spec.kind,
    generatedKey: spec.key,
    generationVersion: version,
    generationRuleVersion: spec.ruleVersion,
    generationFingerprint: spec.fingerprint,
    generationSource: {
      sources: spec.sources,
      professionalReviewRequired: spec.professionalReviewRequired,
      warnings: spec.warnings,
    } satisfies Prisma.InputJsonObject,
    generationInputs: spec.inputs as Prisma.InputJsonObject,
    isComplete: false,
    completedDate: null,
    completionDateKnown: true,
    reminderDays: [30, 14, 7],
  };
}

export class DeadlineService {
  constructor(private prisma: DeadlinePrisma | PrismaClient) {}

  async list(organisationId: string, page = 1, pageSize = 50, viewerRole: 'OWNER' | 'ADMIN' | 'MEMBER' = 'OWNER') {
    const bounds = pageBounds(page, pageSize);
    // Manually entered titles and descriptions are unrestricted text. Until
    // their audience is classified, Members see only generated obligations.
    const where = { organisationId, supersededAt: null, archivedAt: null,
      ...(viewerRole === 'MEMBER' ? MEMBER_DEADLINE_FILTER : {}) };
    const [rows, total] = await Promise.all([
      this.prisma.deadline.findMany({
        where,
        select: viewerRole === 'MEMBER' ? memberDeadlineSelect : undefined,
        orderBy: [{ isComplete: 'asc' }, { dueDate: 'asc' }, { id: 'asc' }],
        skip: bounds.skip,
        take: bounds.pageSize,
      }),
      this.prisma.deadline.count({ where }),
    ]);
    const data = rows.map((row) => viewerRole === 'MEMBER'
      ? publicMemberDeadline(row as MemberDeadlineSource)
      : publicDeadline(row as DeadlineWithGeneration));
    return {
      data,
      total,
      page: bounds.page,
      pageSize: bounds.pageSize,
      hasMore: bounds.skip + data.length < total,
    };
  }

  /**
   * One deadline.
   *
   * The calendar route pages fifty at a time, so following a reference to a
   * single obligation meant walking the year.
   */
  async getById(organisationId: string, id: string, viewerRole: 'OWNER' | 'ADMIN' | 'MEMBER' = 'OWNER') {
    const deadline = await this.prisma.deadline.findFirst({ where: { id, organisationId,
      ...(viewerRole === 'MEMBER' ? MEMBER_DEADLINE_FILTER : {}) },
    select: viewerRole === 'MEMBER' ? memberDeadlineSelect : undefined });
    if (!deadline) throw new AppError(404, 'DEADLINE_NOT_FOUND', 'Deadline not found');
    return viewerRole === 'MEMBER' ? publicMemberDeadline(deadline as MemberDeadlineSource) : deadline;
  }

  async history(organisationId: string, page = 1, pageSize = 50, viewerRole: 'OWNER' | 'ADMIN' | 'MEMBER' = 'OWNER') {
    const bounds = pageBounds(page, pageSize);
    const where = {
      organisationId,
      isAutoGenerated: true,
      ...(viewerRole === 'MEMBER' ? { generatedKind: MEMBER_DEADLINE_FILTER.generatedKind } : {}),
      OR: [{ isComplete: true }, { supersededAt: { not: null } }],
    };
    const [rows, total] = await Promise.all([
      this.prisma.deadline.findMany({
        where,
        select: viewerRole === 'MEMBER' ? memberDeadlineSelect : undefined,
        orderBy: [{ createdAt: 'desc' }, { id: 'desc' }],
        skip: bounds.skip,
        take: bounds.pageSize,
      }),
      this.prisma.deadline.count({ where }),
    ]);
    const data = rows.map((row) => viewerRole === 'MEMBER'
      ? publicMemberDeadline(row as MemberDeadlineSource)
      : publicDeadline(row as DeadlineWithGeneration));
    return {
      data,
      total,
      page: bounds.page,
      pageSize: bounds.pageSize,
      hasMore: bounds.skip + data.length < total,
    };
  }

  async reminderHistory(
    organisationId: string,
    page = 1,
    pageSize = 50,
    filters: { deadlineId?: string; status?: string } = {},
  ) {
    const bounds = pageBounds(page, pageSize);
    const where = {
      organisationId,
      ...(filters.deadlineId ? { deadlineId: filters.deadlineId } : {}),
      ...(filters.status ? { status: filters.status as never } : {}),
    };
    const [rows, total] = await Promise.all([
      this.prisma.deadlineReminderLog.findMany({
        where,
        orderBy: [{ reservedAt: 'desc' }, { id: 'desc' }],
        skip: bounds.skip,
        take: bounds.pageSize,
      }),
      this.prisma.deadlineReminderLog.count({ where }),
    ]);
    const data = rows.map((row) => ({
      id: row.id,
      deadlineId: row.deadlineId,
      deadlineTitle: row.deadlineTitle,
      deadlineDueDate: civilDateFromPrisma(row.deadlineDueDate),
      deadlineScheduleVersion: row.deadlineScheduleVersion,
      deadlineContextKind: row.deadlineSnapshotKnown
        ? 'RECORDED_AT_RESERVATION' as const
        : 'MIGRATION_TIME_CONTEXT' as const,
      deadlineSnapshotKnown: row.deadlineSnapshotKnown,
      deliveryTimingKnown: row.deliveryTimingKnown,
      legacyDeliveryStatus: row.legacyDeliveryStatus as 'SENT' | 'FAILED' | 'SKIPPED' | null,
      legacyRecordedAt: row.legacyRecordedAt?.toISOString() ?? null,
      email: row.email,
      reminderDays: row.reminderDays,
      status: row.status,
      error: row.error,
      reservedAt: row.deliveryTimingKnown ? row.reservedAt.toISOString() : null,
      attemptedAt: row.attemptedAt?.toISOString() ?? null,
      providerRequestStartedAt: row.providerRequestStartedAt?.toISOString() ?? null,
      reconciliationOutcome: row.reconciliationOutcome,
      reconciledAt: row.reconciledAt?.toISOString() ?? null,
      sentAt: row.sentAt?.toISOString() ?? null,
    }));
    return {
      data,
      total,
      page: bounds.page,
      pageSize: bounds.pageSize,
      hasMore: bounds.skip + data.length < total,
    };
  }

  async create(organisationId: string, data: CreateDeadlineRequest, actorUserId: string) {
    try {
      const deadline = await (this.prisma as PrismaClient).$transaction(async (tx) => {
        const created = await tx.deadline.create({
          data: {
            organisationId,
            title: data.title,
            description: data.description,
            dueDate: prismaDateFromCivil(data.dueDate),
            reminderDays: normalizeReminderDays(data.reminderDays ?? [30, 14, 7]),
            ...('profileRuleKey' in data && data.profileRuleKey
              ? { profileRuleKey: data.profileRuleKey }
              : {}),
          },
        });
        await tx.deadlineChangeAudit.create({ data: {
          organisationId, deadlineId: created.id, actorUserId, action: 'CREATE',
          previousState: null, nextState: 'OPEN',
          changedFields: ['title', 'description', 'dueDate', 'reminderDays',
            ...('profileRuleKey' in data && data.profileRuleKey ? ['profileRuleKey'] : [])],
          previousUpdatedAt: null, nextUpdatedAt: created.updatedAt,
        } });
        return created;
      });
      return publicDeadline(deadline as DeadlineWithGeneration);
    } catch (error) {
      if (isUniqueConstraintError(error) && 'profileRuleKey' in data && data.profileRuleKey) {
        throw new AppError(409, 'PROFILE_REVIEW_ALREADY_SCHEDULED', 'That profile review already has a current deadline.');
      }
      throw error;
    }
  }

  async update(organisationId: string, id: string, data: UpdateDeadlineRequest, actorUserId: string) {
    return (this.prisma as PrismaClient).$transaction((tx) => this.updateInTransaction(tx, organisationId, id, data, actorUserId));
  }

  private async updateInTransaction(client: Prisma.TransactionClient, organisationId: string, id: string,
    data: UpdateDeadlineRequest, actorUserId: string) {
    const { expectedUpdatedAt, ...changes } = data;
    const expectedUpdatedAtInstant = new Date(expectedUpdatedAt);
    const deadline = await client.deadline.findFirst({
      where: { id, organisationId, archivedAt: null },
    });

    if (!deadline) {
      throw new AppError(404, 'DEADLINE_NOT_FOUND', 'Deadline not found');
    }
    if (deadline.supersededAt) {
      throw new AppError(409, 'DEADLINE_SUPERSEDED', 'This generated deadline is historical and cannot be changed.');
    }
    if (deadline.updatedAt.getTime() !== expectedUpdatedAtInstant.getTime()) {
      throw new AppError(
        409,
        'DEADLINE_UPDATE_CONFLICT',
        'This deadline changed since it was loaded. Refresh and review the latest values.',
      );
    }

    if (deadline.isAutoGenerated) {
      const changedFields = Object.entries(changes)
        .filter(([, value]) => value !== undefined)
        .map(([key]) => key);
      if (changedFields.length !== 1 || changedFields[0] !== 'isComplete' || data.isComplete !== true) {
        throw new AppError(
          409,
          'GENERATED_DEADLINE_IMMUTABLE',
          'Generated deadlines cannot be edited, reopened, rescheduled, or deleted.',
        );
      }

      const completed = await client.deadline.updateMany({
        where: {
          id,
          organisationId,
          archivedAt: null,
          supersededAt: null,
          isComplete: false,
          updatedAt: expectedUpdatedAtInstant,
        },
        data: { isComplete: true, completedDate: new Date(), completionDateKnown: true },
      });
      if (completed.count !== 1) {
        throw new AppError(409, 'DEADLINE_ALREADY_COMPLETED', 'This generated deadline is already complete or changed.');
      }
      const updated = await client.deadline.findUniqueOrThrow({ where: { id } });
      await client.deadlineChangeAudit.create({ data: {
        organisationId, deadlineId: id, actorUserId, action: 'COMPLETE',
        previousState: 'OPEN', nextState: 'COMPLETE', changedFields: ['isComplete', 'completedDate'],
        previousUpdatedAt: deadline.updatedAt, nextUpdatedAt: updated.updatedAt,
      } });
      return publicDeadline(updated as DeadlineWithGeneration);
    }

    const changedFields = Object.entries(changes).filter(([, value]) => value !== undefined).map(([key]) => key).sort();
    if (changedFields.length === 0) {
      throw new AppError(400, 'DEADLINE_UPDATE_EMPTY', 'Choose a deadline field to update.');
    }

    const nextReminderDays = changes.reminderDays
      ? normalizeReminderDays(changes.reminderDays)
      : undefined;
    const dueDateChanged = changes.dueDate !== undefined && changes.dueDate !== civilDateFromPrisma(deadline.dueDate);
    const reopened = changes.isComplete === false && deadline.isComplete;
    const newlyCompleted = changes.isComplete === true && !deadline.isComplete;
    const scheduleChanged = dueDateChanged || reopened;

    try {
      const updated = await client.deadline.updateMany({
        where: {
          id,
          organisationId,
          archivedAt: null,
          supersededAt: null,
          updatedAt: expectedUpdatedAtInstant,
        },
        data: {
          title: changes.title,
          description: changes.description,
          dueDate: changes.dueDate ? prismaDateFromCivil(changes.dueDate) : undefined,
          isComplete: changes.isComplete,
          completedDate: newlyCompleted ? new Date() : reopened ? null : undefined,
          completionDateKnown: newlyCompleted || reopened ? true : undefined,
          reminderDays: nextReminderDays,
          scheduleVersion: scheduleChanged ? { increment: 1 } : undefined,
        },
      });
      if (updated.count !== 1) {
        throw new AppError(
          409,
          'DEADLINE_UPDATE_CONFLICT',
          'This deadline changed while it was being saved. Refresh and try again.',
        );
      }
      const current = await client.deadline.findUniqueOrThrow({ where: { id } });
      await client.deadlineChangeAudit.create({ data: {
        organisationId, deadlineId: id, actorUserId,
        action: newlyCompleted ? 'COMPLETE' : 'UPDATE',
        previousState: deadline.isComplete ? 'COMPLETE' : 'OPEN',
        nextState: current.isComplete ? 'COMPLETE' : 'OPEN',
        changedFields: [...changedFields,
          ...(newlyCompleted || reopened ? ['completedDate'] : []),
          ...(scheduleChanged ? ['scheduleVersion'] : [])].sort(),
        previousUpdatedAt: deadline.updatedAt, nextUpdatedAt: current.updatedAt,
      } });
      return publicDeadline(current as DeadlineWithGeneration);
    } catch (error) {
      if (isUniqueConstraintError(error) && reopened && deadline.profileRuleKey) {
        throw new AppError(
          409,
          'PROFILE_REVIEW_ALREADY_SCHEDULED',
          'A newer current deadline already exists for that profile review.',
        );
      }
      throw error;
    }
  }

  async remove(organisationId: string, id: string, expectedUpdatedAt: string, actorUserId: string) {
    return (this.prisma as PrismaClient).$transaction((tx) => this.removeInTransaction(tx, organisationId, id, expectedUpdatedAt, actorUserId));
  }

  private async removeInTransaction(client: Prisma.TransactionClient, organisationId: string, id: string,
    expectedUpdatedAt: string, actorUserId: string) {
    const expectedUpdatedAtInstant = new Date(expectedUpdatedAt);
    const deadline = await client.deadline.findFirst({
      where: { id, organisationId, archivedAt: null },
    });

    if (!deadline) {
      throw new AppError(404, 'DEADLINE_NOT_FOUND', 'Deadline not found');
    }
    if (deadline.isAutoGenerated) {
      throw new AppError(409, 'GENERATED_DEADLINE_IMMUTABLE', 'Generated deadlines cannot be deleted.');
    }
    if (deadline.updatedAt.getTime() !== expectedUpdatedAtInstant.getTime()) {
      throw new AppError(
        409,
        'DEADLINE_UPDATE_CONFLICT',
        'This deadline changed since it was loaded. Refresh before deleting it.',
      );
    }

    const archived = await client.deadline.updateMany({
      where: {
        id,
        organisationId,
        archivedAt: null,
        updatedAt: expectedUpdatedAtInstant,
      },
      data: { archivedAt: new Date() },
    });
    if (archived.count !== 1) {
      throw new AppError(
        409,
        'DEADLINE_UPDATE_CONFLICT',
        'This deadline changed while it was being deleted. Refresh and try again.',
      );
    }
    const current = await client.deadline.findUniqueOrThrow({ where: { id } });
    await client.deadlineChangeAudit.create({ data: {
      organisationId, deadlineId: id, actorUserId, action: 'ARCHIVE',
      previousState: deadline.isComplete ? 'COMPLETE' : 'OPEN', nextState: 'ARCHIVED',
      changedFields: ['archivedAt'],
      previousUpdatedAt: deadline.updatedAt, nextUpdatedAt: current.updatedAt,
    } });
  }

  async reconcileGeneratedDeadlines(organisationId: string, actorUserId: string) {
    await this.prisma.$queryRaw`SELECT "id" FROM "Organisation" WHERE "id" = ${organisationId} FOR UPDATE`;
    const organisation = await this.prisma.organisation.findUniqueOrThrow({
      where: { id: organisationId },
      select: {
        financialYearEnd: true,
        legalForm: true,
        legalFormConfirmedAt: true,
        incorporationDate: true,
        memberCount: true,
        constitutionPermitsWrittenResolutions: true,
        lastActualAgmDate: true,
        lastUnanimousAnnualMemberResolutionDate: true,
        croAnnualReturnDate: true,
        croAnnualReturnDateConfirmedAt: true,
      },
    });

    // Derive member count from the register when populated; fall back to the
    // manually entered memberCount when no Member rows exist yet.
    const registeredMemberCount = await this.prisma.member.count({
      where: { organisationId, dateCeased: null },
    });
    const effectiveMemberCount = registeredMemberCount > 0
      ? registeredMemberCount
      : organisation.memberCount;

    const desired = deriveIrishGovernanceDeadlines({
      financialYearEnd: nullableCivilDateFromPrisma(organisation.financialYearEnd),
      legalForm: organisation.legalForm,
      legalFormConfirmedAt: organisation.legalFormConfirmedAt,
      incorporationDate: nullableCivilDateFromPrisma(organisation.incorporationDate),
      memberCount: effectiveMemberCount,
      constitutionPermitsWrittenResolutions: organisation.constitutionPermitsWrittenResolutions,
      lastActualAgmDate: nullableCivilDateFromPrisma(organisation.lastActualAgmDate),
      lastUnanimousAnnualMemberResolutionDate: nullableCivilDateFromPrisma(
        organisation.lastUnanimousAnnualMemberResolutionDate,
      ),
      croAnnualReturnDate: nullableCivilDateFromPrisma(organisation.croAnnualReturnDate),
      croAnnualReturnDateConfirmedAt: organisation.croAnnualReturnDateConfirmedAt,
    });

    const allGenerated = await this.prisma.deadline.findMany({
      where: { organisationId, isAutoGenerated: true, generatedKey: { not: null } },
      orderBy: [{ generationVersion: 'asc' }, { createdAt: 'asc' }],
    });
    const currentByKey = new Map(
      allGenerated
        .filter((deadline) => deadline.supersededAt === null && deadline.archivedAt === null && deadline.generatedKey)
        .map((deadline) => [deadline.generatedKey!, deadline]),
    );
    const versionByKey = new Map<string, number>();
    for (const deadline of allGenerated) {
      if (!deadline.generatedKey || !deadline.generationVersion) continue;
      versionByKey.set(
        deadline.generatedKey,
        Math.max(versionByKey.get(deadline.generatedKey) ?? 0, deadline.generationVersion),
      );
    }

    const desiredByKey = new Map(desired.map((spec) => [spec.key, spec]));
    const now = new Date();

    for (const [key, current] of currentByKey) {
      const spec = desiredByKey.get(key);
      if (!spec) {
        const superseded = await this.prisma.deadline.update({
          where: { id: current.id },
          data: { supersededAt: now, supersessionReason: 'INPUT_REMOVED' },
        });
        await this.prisma.deadlineChangeAudit.create({ data: {
          organisationId, deadlineId: current.id, actorUserId, action: 'SUPERSEDE',
          previousState: current.isComplete ? 'COMPLETE' : 'OPEN', nextState: 'SUPERSEDED',
          changedFields: ['supersededAt', 'supersessionReason'],
          previousUpdatedAt: current.updatedAt, nextUpdatedAt: superseded.updatedAt,
        } });
        continue;
      }
      if (
        current.generationFingerprint === spec.fingerprint &&
        current.generationRuleVersion === spec.ruleVersion &&
        civilDateFromPrisma(current.dueDate) === spec.dueDate
      ) {
        desiredByKey.delete(key);
        continue;
      }

      const reason = current.generationRuleVersion !== spec.ruleVersion
        ? 'RULE_CHANGED'
        : current.isComplete
          ? 'RECURRENCE_ADVANCED'
          : 'INPUT_CHANGED';
      await this.prisma.deadline.update({
        where: { id: current.id },
        data: { supersededAt: now, supersessionReason: reason },
      });
      const version = (versionByKey.get(key) ?? 0) + 1;
      const successor = await this.prisma.deadline.create({
        data: generationData(organisationId, spec, version),
      });
      const superseded = await this.prisma.deadline.update({
        where: { id: current.id },
        data: { supersededById: successor.id },
      });
      await this.prisma.deadlineChangeAudit.create({ data: {
        organisationId, deadlineId: current.id, actorUserId, action: 'SUPERSEDE',
        previousState: current.isComplete ? 'COMPLETE' : 'OPEN', nextState: 'SUPERSEDED',
        changedFields: ['supersededAt', 'supersessionReason', 'supersededById'],
        previousUpdatedAt: current.updatedAt, nextUpdatedAt: superseded.updatedAt,
      } });
      await this.prisma.deadlineChangeAudit.create({ data: {
        organisationId, deadlineId: successor.id, actorUserId, action: 'GENERATE',
        previousState: null, nextState: 'OPEN',
        changedFields: ['generationVersion', 'generationRuleVersion', 'dueDate', 'generationSource'],
        previousUpdatedAt: null, nextUpdatedAt: successor.updatedAt,
      } });
      versionByKey.set(key, version);
      desiredByKey.delete(key);
    }

    for (const spec of desiredByKey.values()) {
      const version = (versionByKey.get(spec.key) ?? 0) + 1;
      const created = await this.prisma.deadline.create({
        data: generationData(organisationId, spec, version),
      });
      await this.prisma.deadlineChangeAudit.create({ data: {
        organisationId, deadlineId: created.id, actorUserId, action: 'GENERATE',
        previousState: null, nextState: 'OPEN',
        changedFields: ['generationVersion', 'generationRuleVersion', 'dueDate', 'generationSource'],
        previousUpdatedAt: null, nextUpdatedAt: created.updatedAt,
      } });
      versionByKey.set(spec.key, version);
    }
  }
}
