import type { PrismaClient } from '@prisma/client';
import type { CreateDeadlineRequest, UpdateDeadlineRequest } from '@charitypilot/shared';
import { AppError } from '../utils/errors.js';

type DeadlinePrisma = Pick<PrismaClient, 'deadline' | 'organisation'>;

export class DeadlineService {
  constructor(private prisma: DeadlinePrisma) {}

  async list(organisationId: string, page = 1, pageSize = 50) {
    const skip = (page - 1) * pageSize;
    const [data, total] = await Promise.all([
      this.prisma.deadline.findMany({
        where: { organisationId },
        orderBy: { dueDate: 'asc' },
        skip,
        take: pageSize,
      }),
      this.prisma.deadline.count({ where: { organisationId } }),
    ]);
    return { data, total, page, pageSize, hasMore: skip + data.length < total };
  }

  async create(organisationId: string, data: CreateDeadlineRequest) {
    return this.prisma.deadline.create({
      data: {
        organisationId,
        title: data.title,
        description: data.description,
        dueDate: new Date(data.dueDate),
        reminderDays: data.reminderDays ?? [30, 14, 7],
      },
    });
  }

  async update(organisationId: string, id: string, data: UpdateDeadlineRequest) {
    const deadline = await this.prisma.deadline.findFirst({
      where: { id, organisationId },
    });

    if (!deadline) {
      throw new AppError(404, 'DEADLINE_NOT_FOUND', 'Deadline not found');
    }

    return this.prisma.deadline.update({
      where: { id },
      data: {
        title: data.title,
        description: data.description,
        dueDate: data.dueDate ? new Date(data.dueDate) : undefined,
        isComplete: data.isComplete,
        completedDate: data.isComplete ? new Date() : data.isComplete === false ? null : undefined,
        reminderDays: data.reminderDays,
      },
    });
  }

  async remove(organisationId: string, id: string) {
    const deadline = await this.prisma.deadline.findFirst({
      where: { id, organisationId },
    });

    if (!deadline) {
      throw new AppError(404, 'DEADLINE_NOT_FOUND', 'Deadline not found');
    }

    await this.prisma.deadline.delete({ where: { id } });
  }

  async generateAutoDeadlines(organisationId: string) {
    const org = await this.prisma.organisation.findUniqueOrThrow({
      where: { id: organisationId },
    });
    const staleAutoDeadlineFilters: Array<{ title: string } | { title: { startsWith: string } }> = [];

    const deadlines: { title: string; dueDate: Date; description: string }[] = [];

    // Annual Report filing deadline: financial year end + 10 months
    if (org.financialYearEnd) {
      const fyEnd = new Date(org.financialYearEnd);
      const filingDeadline = new Date(fyEnd);
      filingDeadline.setMonth(filingDeadline.getMonth() + 10);
      deadlines.push({
        title: `Annual Report filing deadline (${fyEnd.getFullYear()})`,
        description: 'Charities Regulator Annual Report filing deadline: 10 months after financial year end.',
        dueDate: filingDeadline,
      });
    } else {
      staleAutoDeadlineFilters.push({ title: { startsWith: 'Annual Report filing deadline (' } });
    }

    // AGM due date: within 15 months of previous AGM
    if (org.lastAgmDate) {
      const lastAgm = new Date(org.lastAgmDate);
      const agmDue = new Date(lastAgm);
      agmDue.setMonth(agmDue.getMonth() + 15);
      deadlines.push({
        title: 'AGM due date',
        description: 'Indicative AGM planning date based on the last AGM recorded in the organisation profile.',
        dueDate: agmDue,
      });
    } else {
      staleAutoDeadlineFilters.push({ title: 'AGM due date' });
    }

    if (staleAutoDeadlineFilters.length > 0) {
      await this.prisma.deadline.deleteMany({
        where: {
          organisationId,
          isAutoGenerated: true,
          isComplete: false,
          OR: staleAutoDeadlineFilters,
        },
      });
    }

    for (const d of deadlines) {
      const existing = await this.prisma.deadline.findFirst({
        where: {
          organisationId,
          title: d.title,
          isAutoGenerated: true,
        },
      });

      if (existing) {
        await this.prisma.deadline.update({
          where: { id: existing.id },
          data: {
            description: d.description,
            dueDate: d.dueDate,
          },
        });
      } else {
        await this.prisma.deadline.create({
          data: {
            organisationId,
            title: d.title,
            description: d.description,
            dueDate: d.dueDate,
            isAutoGenerated: true,
            reminderDays: [30, 14, 7],
          },
        });
      }
    }
  }
}
