import { readFileSync, writeFileSync, renameSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';

export const COLORS = ['blue', 'green'];

const STATUS_HISTORY_LIMIT = 50;

export function otherColor(color) {
  if (color === 'blue') return 'green';
  if (color === 'green') return 'blue';
  throw new Error(`Invalid color: ${color}. Must be 'blue' or 'green'.`);
}

export function readState(stateDir) {
  const stateFile = join(stateDir, 'state.json');
  try {
    const content = readFileSync(stateFile, 'utf8');
    return JSON.parse(content);
  } catch (err) {
    // If file is missing, return null
    if (err.code === 'ENOENT') {
      return null;
    }
    // If file is corrupt (parse error or read error), return null with corrupt flag
    return { corrupt: true };
  }
}

export function writeState(stateDir, state) {
  mkdirSync(stateDir, { recursive: true });
  const stateFile = join(stateDir, 'state.json');
  const tmpFile = join(stateDir, 'state.json.tmp');

  // Write to temp file
  writeFileSync(tmpFile, JSON.stringify(state, null, 2));

  // Atomic rename
  renameSync(tmpFile, stateFile);
}

export function renderUpstreams(color) {
  if (color === 'blue') {
    return [
      '# Generated by scripts/bluegreen-deploy.mjs — do not edit by hand.',
      '# The engine writes the live colour\'s upstreams and gracefully reloads Caddy.',
      'reverse_proxy /api/* api-blue:3002',
      'reverse_proxy web-blue:3003',
      '',
    ].join('\n');
  } else if (color === 'green') {
    return [
      '# Generated by deployment engine — do not edit by hand.',
      '# Upstream routing for active green deployment.',
      'reverse_proxy /api/* api-green:3002',
      'reverse_proxy web-green:3003',
      '',
    ].join('\n');
  }
  throw new Error(`Invalid color: ${color}. Must be 'blue' or 'green'.`);
}

export function releaseDirFor(stateDir, commit) {
  return join(stateDir, 'releases', commit);
}

export function prunePlan(releases, keep = 3, activeCommit) {
  // releases is an array of {commit, mtime}
  // returns array of commits to delete
  // keeps newest `keep` releases
  // but NEVER deletes the active commit

  if (!Array.isArray(releases)) {
    return [];
  }

  // Sort by mtime descending (newest first)
  const sorted = [...releases].sort((a, b) => (b.mtime ?? 0) - (a.mtime ?? 0));

  // Keep the newest `keep` releases
  const toKeep = new Set(sorted.slice(0, keep).map(r => r.commit));

  // Also keep the active commit if provided
  if (activeCommit) {
    toKeep.add(activeCommit);
  }

  // Return all commits that are NOT in the toKeep set
  const toDelete = releases
    .map(r => r.commit)
    .filter(commit => !toKeep.has(commit));

  return toDelete;
}

export function deployStatus(stateDir) {
  const statusFile = join(stateDir, 'deploy-status.json');
  try {
    const content = readFileSync(statusFile, 'utf8');
    return JSON.parse(content);
  } catch (err) {
    // If file is missing or corrupt, return null
    if (err.code === 'ENOENT') {
      return null;
    }
    // If file is corrupt (parse error), return null
    return null;
  }
}

export function writeDeployStatus(stateDir, phase, detail) {
  mkdirSync(stateDir, { recursive: true });
  const statusFile = join(stateDir, 'deploy-status.json');
  const tmpFile = join(stateDir, 'deploy-status.json.tmp');

  // Read existing status or create new
  let status = deployStatus(stateDir) || { history: [] };

  // Ensure history is an array
  if (!Array.isArray(status.history)) {
    status.history = [];
  }

  // Add new entry
  const entry = {
    timestamp: new Date().toISOString(),
    phase,
    detail,
  };

  status.history.push(entry);

  // Keep only the last 50 entries
  if (status.history.length > STATUS_HISTORY_LIMIT) {
    status.history = status.history.slice(-STATUS_HISTORY_LIMIT);
  }

  // Update the status object with latest phase and detail
  status.phase = phase;
  status.detail = detail;
  status.timestamp = entry.timestamp;

  // Write to temp file
  writeFileSync(tmpFile, JSON.stringify(status, null, 2));

  // Atomic rename
  renameSync(tmpFile, statusFile);
}
