import assert from 'node:assert/strict';
import * as fs from 'node:fs';
import { readFileSync, rmSync, mkdtempSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import test from 'node:test';
import {
  COLORS,
  otherColor,
  readState,
  writeState,
  renderUpstreams,
  releaseDirFor,
  prunePlan,
  deployStatus,
  writeDeployStatus,
} from './lib.mjs';

const repoRoot = dirname(dirname(dirname(fileURLToPath(import.meta.url))));

test('COLORS is an array with blue and green', () => {
  assert.deepEqual(COLORS, ['blue', 'green']);
});

test('otherColor switches blue to green', () => {
  assert.equal(otherColor('blue'), 'green');
});

test('otherColor switches green to blue', () => {
  assert.equal(otherColor('green'), 'blue');
});

test('otherColor throws on invalid color', () => {
  assert.throws(() => otherColor('red'), /Invalid color/);
  assert.throws(() => otherColor('invalid'), /Invalid color/);
  assert.throws(() => otherColor(null), /Invalid color/);
});

test('renderUpstreams(blue) outputs exact blue lines matching example file', () => {
  const body = renderUpstreams('blue');
  const exampleFile = join(repoRoot, 'caddy', 'active-upstreams.example.caddy');
  const trackedContent = readFileSync(exampleFile, 'utf8');
  assert.equal(body, trackedContent, 'renderUpstreams(blue) must equal the tracked example file byte-for-byte');
});

test('renderUpstreams(green) names only green services', () => {
  const body = renderUpstreams('green');
  assert.match(body, /api-green:3002/);
  assert.match(body, /web-green:3003/);
  // Verify no blue service names (reverse_proxy lines must use green only)
  assert.doesNotMatch(body, /reverse_proxy.*api-blue/);
  assert.doesNotMatch(body, /reverse_proxy.*web-blue/);
});

test('renderUpstreams uses unified template for both colors', () => {
  const blue = renderUpstreams('blue');
  const green = renderUpstreams('green');
  // Both should have the same header
  assert.match(blue, /Generated by scripts\/bluegreen-deploy\.mjs/);
  assert.match(green, /Generated by scripts\/bluegreen-deploy\.mjs/);
  // Verify template is truly unified: difference is only in service names
  const blueLine1 = blue.split('\n')[2];
  const greenLine1 = green.split('\n')[2];
  assert.equal(blueLine1, 'reverse_proxy /api/* api-blue:3002');
  assert.equal(greenLine1, 'reverse_proxy /api/* api-green:3002');
});

test('renderUpstreams throws on invalid color', () => {
  assert.throws(() => renderUpstreams('red'), /Invalid color/);
  assert.throws(() => renderUpstreams('invalid'), /Invalid color/);
});

test('readState returns null for missing file', () => {
  const scratchDir = mkdtempSync(join(tmpdir(), 'bluegreen-test-'));
  try {
    const stateDir = join(scratchDir, 'nonexistent');
    const result = readState(stateDir);
    assert.equal(result, null);
  } finally {
    rmSync(scratchDir, { recursive: true });
  }
});

test('readState returns null with corrupt flag for corrupted state file', () => {
  const scratchDir = mkdtempSync(join(tmpdir(), 'bluegreen-test-'));
  try {
    const stateDir = scratchDir;
    const stateFile = join(stateDir, 'state.json');
    writeFileSync(stateFile, 'not valid json {');
    const result = readState(stateDir);
    assert.equal(result.corrupt, true);
  } finally {
    rmSync(scratchDir, { recursive: true });
  }
});

test('readState tolerates a corrupt state file by reporting, not throwing', () => {
  const scratchDir = mkdtempSync(join(tmpdir(), 'bluegreen-test-'));
  try {
    const stateDir = scratchDir;
    const stateFile = join(stateDir, 'state.json');
    writeFileSync(stateFile, 'garbage garbage garbage');
    const result = readState(stateDir);
    assert.ok(result);
    assert.equal(result.corrupt, true);
  } finally {
    rmSync(scratchDir, { recursive: true });
  }
});

test('writeState and readState round-trip state data', () => {
  const scratchDir = mkdtempSync(join(tmpdir(), 'bluegreen-test-'));
  try {
    const stateDir = scratchDir;
    const state = { activeColor: 'blue', commit: 'abc123', deployedAt: '2026-08-31T12:00:00Z' };
    writeState(stateDir, state);
    const result = readState(stateDir);
    assert.deepEqual(result, state);
  } finally {
    rmSync(scratchDir, { recursive: true });
  }
});

test('writeState uses atomic rename (tmp written before rename, verified by examining file write order)', () => {
  const scratchDir = mkdtempSync(join(tmpdir(), 'bluegreen-test-'));
  try {
    const stateDir = scratchDir;
    const originalState = { activeColor: 'blue', commit: 'abc123', deployedAt: '2026-08-31T12:00:00Z' };

    // Write an initial state
    writeState(stateDir, originalState);

    // Verify the pattern: writeState creates a tmp file in the same directory as target
    const stateFile = join(stateDir, 'state.json');
    const tmpFile = join(stateDir, 'state.json.tmp');

    // Verify tmp and final paths are in the same directory (atomic rename guarantee)
    assert.equal(dirname(tmpFile), dirname(stateFile));

    // Verify successful write has no tmp remnant
    try {
      readFileSync(tmpFile);
      assert.fail('No temp file should exist after successful write');
    } catch (err) {
      assert.equal(err.code, 'ENOENT');
    }

    // Verify that round-trip preserves state (tmp file was fully written before being renamed)
    const result = readState(stateDir);
    assert.deepEqual(result, originalState);

    // Update state and verify atomicity pattern holds
    const newState = { activeColor: 'green', commit: 'def456', deployedAt: '2026-08-31T13:00:00Z' };
    writeState(stateDir, newState);

    // Still no tmp file after successful rename
    try {
      readFileSync(tmpFile);
      assert.fail('No temp file should exist after atomic write');
    } catch (err) {
      assert.equal(err.code, 'ENOENT');
    }

    // State round-trips correctly (proving tmp file was fully written before rename)
    const updated = readState(stateDir);
    assert.deepEqual(updated, newState);
  } finally {
    rmSync(scratchDir, { recursive: true });
  }
});

test('releaseDirFor returns correct path structure', () => {
  const stateDir = 'path/to/state';
  const commit = 'abc123def456';
  const result = releaseDirFor(stateDir, commit);
  assert.match(result, /path[/\\]to[/\\]state[/\\]releases[/\\]abc123def456/);
});

test('prunePlan keeps the 3 newest releases', () => {
  const releases = [
    { commit: 'oldest', mtime: 1000 },
    { commit: 'middle', mtime: 2000 },
    { commit: 'newer', mtime: 3000 },
    { commit: 'newest', mtime: 4000 },
    { commit: 'very-new', mtime: 5000 },
  ];
  const toDelete = prunePlan(releases, 3);
  assert.deepEqual(toDelete.sort(), ['middle', 'oldest']);
  assert.ok(toDelete.includes('oldest'));
  assert.ok(toDelete.includes('middle'));
  assert.ok(!toDelete.includes('newer'));
  assert.ok(!toDelete.includes('newest'));
  assert.ok(!toDelete.includes('very-new'));
});

test('prunePlan never deletes the active commit even if oldest', () => {
  const releases = [
    { commit: 'active-old', mtime: 1000 },
    { commit: 'middle', mtime: 2000 },
    { commit: 'newer', mtime: 3000 },
    { commit: 'newest', mtime: 4000 },
  ];
  const toDelete = prunePlan(releases, 3, 'active-old');
  // Should keep: active-old (explicit), newest, newer (and middle for top 3)
  // Actually: keep 3 newest (newest, newer, middle) PLUS active-old
  assert.ok(!toDelete.includes('active-old'), 'active commit must not be deleted');
});

test('prunePlan respects custom keep count', () => {
  const releases = [
    { commit: 'c1', mtime: 1000 },
    { commit: 'c2', mtime: 2000 },
    { commit: 'c3', mtime: 3000 },
    { commit: 'c4', mtime: 4000 },
    { commit: 'c5', mtime: 5000 },
  ];
  const toDelete = prunePlan(releases, 2);
  assert.deepEqual(toDelete.sort(), ['c1', 'c2', 'c3']);
  assert.ok(!toDelete.includes('c4'));
  assert.ok(!toDelete.includes('c5'));
});

test('prunePlan handles empty releases array', () => {
  const toDelete = prunePlan([]);
  assert.deepEqual(toDelete, []);
});

test('deployStatus returns null for missing status file', () => {
  const scratchDir = mkdtempSync(join(tmpdir(), 'bluegreen-test-'));
  try {
    const stateDir = join(scratchDir, 'nonexistent');
    const result = deployStatus(stateDir);
    assert.equal(result, null);
  } finally {
    rmSync(scratchDir, { recursive: true });
  }
});

test('deployStatus returns null for corrupted status file', () => {
  const scratchDir = mkdtempSync(join(tmpdir(), 'bluegreen-test-'));
  try {
    const stateDir = scratchDir;
    const statusFile = join(stateDir, 'deploy-status.json');
    writeFileSync(statusFile, 'not valid json {');
    const result = deployStatus(stateDir);
    assert.equal(result, null);
  } finally {
    rmSync(scratchDir, { recursive: true });
  }
});

test('writeDeployStatus creates initial status with timestamp and history', () => {
  const scratchDir = mkdtempSync(join(tmpdir(), 'bluegreen-test-'));
  try {
    const stateDir = scratchDir;
    writeDeployStatus(stateDir, 'initializing', 'Started deployment');
    const result = deployStatus(stateDir);
    assert.ok(result);
    assert.equal(result.phase, 'initializing');
    assert.equal(result.detail, 'Started deployment');
    assert.ok(result.timestamp);
    assert.ok(Array.isArray(result.history));
    assert.equal(result.history.length, 1);
    assert.equal(result.history[0].phase, 'initializing');
    assert.equal(result.history[0].detail, 'Started deployment');
  } finally {
    rmSync(scratchDir, { recursive: true });
  }
});

test('writeDeployStatus appends to history and updates current status', () => {
  const scratchDir = mkdtempSync(join(tmpdir(), 'bluegreen-test-'));
  try {
    const stateDir = scratchDir;
    writeDeployStatus(stateDir, 'phase1', 'detail1');
    writeDeployStatus(stateDir, 'phase2', 'detail2');
    const result = deployStatus(stateDir);
    assert.equal(result.phase, 'phase2');
    assert.equal(result.detail, 'detail2');
    assert.equal(result.history.length, 2);
    assert.equal(result.history[0].phase, 'phase1');
    assert.equal(result.history[1].phase, 'phase2');
  } finally {
    rmSync(scratchDir, { recursive: true });
  }
});

test('writeDeployStatus caps history at 50 entries', () => {
  const scratchDir = mkdtempSync(join(tmpdir(), 'bluegreen-test-'));
  try {
    const stateDir = scratchDir;
    // Write 60 entries
    for (let i = 0; i < 60; i++) {
      writeDeployStatus(stateDir, `phase${i}`, `detail${i}`);
    }
    const result = deployStatus(stateDir);
    assert.equal(result.history.length, 50);
    // Should keep the last 50 entries (entries 10-59)
    assert.equal(result.history[0].phase, 'phase10');
    assert.equal(result.history[49].phase, 'phase59');
  } finally {
    rmSync(scratchDir, { recursive: true });
  }
});

test('writeDeployStatus uses atomic rename (tmp written before rename, verified by examining file order)', () => {
  const scratchDir = mkdtempSync(join(tmpdir(), 'bluegreen-test-'));
  try {
    const stateDir = scratchDir;

    // Write initial status
    writeDeployStatus(stateDir, 'phase1', 'detail1');
    const initialStatus = deployStatus(stateDir);
    assert.equal(initialStatus.phase, 'phase1');

    // Verify the pattern: tmp and final paths are in the same directory
    const statusFile = join(stateDir, 'deploy-status.json');
    const tmpFile = join(stateDir, 'deploy-status.json.tmp');
    assert.equal(dirname(tmpFile), dirname(statusFile), 'tmp and final paths must be in same directory for atomic rename');

    // Verify successful write has no tmp remnant
    try {
      readFileSync(tmpFile);
      assert.fail('No temp file should exist after successful write');
    } catch (err) {
      assert.equal(err.code, 'ENOENT');
    }

    // Verify that round-trip preserves status (tmp file was fully written before being renamed)
    const result = deployStatus(stateDir);
    assert.equal(result.phase, 'phase1');
    assert.equal(result.history.length, 1);

    // Write another status and verify atomicity pattern holds
    writeDeployStatus(stateDir, 'phase2', 'detail2');

    // Still no tmp file after successful rename
    try {
      readFileSync(tmpFile);
      assert.fail('No temp file should exist after atomic write');
    } catch (err) {
      assert.equal(err.code, 'ENOENT');
    }

    // Status round-trips correctly (proving tmp file was fully written before rename)
    const updated = deployStatus(stateDir);
    assert.equal(updated.phase, 'phase2');
    assert.equal(updated.history.length, 2);
  } finally {
    rmSync(scratchDir, { recursive: true });
  }
});

test('writeDeployStatus includes ISO timestamp in each history entry', () => {
  const scratchDir = mkdtempSync(join(tmpdir(), 'bluegreen-test-'));
  try {
    const stateDir = scratchDir;
    writeDeployStatus(stateDir, 'test', 'detail');
    const result = deployStatus(stateDir);
    const timestamp = result.history[0].timestamp;
    // Should be valid ISO format
    assert.ok(/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}/.test(timestamp));
  } finally {
    rmSync(scratchDir, { recursive: true });
  }
});
