import assert from 'node:assert/strict';
import fs from 'node:fs';
import { readFileSync, rmSync, mkdtempSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import test from 'node:test';
import {
  COLORS,
  otherColor,
  readState,
  writeState,
  renderUpstreams,
  releaseDirFor,
  prunePlan,
  deployStatus,
  writeDeployStatus,
} from './lib.mjs';

const repoRoot = dirname(dirname(dirname(fileURLToPath(import.meta.url))));

test('COLORS is an array with blue and green', () => {
  assert.deepEqual(COLORS, ['blue', 'green']);
});

test('otherColor switches blue to green', () => {
  assert.equal(otherColor('blue'), 'green');
});

test('otherColor switches green to blue', () => {
  assert.equal(otherColor('green'), 'blue');
});

test('otherColor throws on invalid color', () => {
  assert.throws(() => otherColor('red'), /Invalid color/);
  assert.throws(() => otherColor('invalid'), /Invalid color/);
  assert.throws(() => otherColor(null), /Invalid color/);
});

test('renderUpstreams(blue) outputs exact blue lines matching example file', () => {
  const body = renderUpstreams('blue');
  const exampleFile = join(repoRoot, 'caddy', 'active-upstreams.example.caddy');
  const trackedContent = readFileSync(exampleFile, 'utf8');
  assert.equal(body, trackedContent, 'renderUpstreams(blue) must equal the tracked example file byte-for-byte');
});

test('renderUpstreams(green) names only green services', () => {
  const body = renderUpstreams('green');
  assert.match(body, /api-green:3002/);
  assert.match(body, /web-green:3003/);
  // Verify no blue service names (reverse_proxy lines must use green only)
  assert.doesNotMatch(body, /reverse_proxy.*api-blue/);
  assert.doesNotMatch(body, /reverse_proxy.*web-blue/);
});

test('renderUpstreams uses unified template for both colors', () => {
  const blue = renderUpstreams('blue');
  const green = renderUpstreams('green');
  // Both should have the same header
  assert.match(blue, /Generated by scripts\/bluegreen-deploy\.mjs/);
  assert.match(green, /Generated by scripts\/bluegreen-deploy\.mjs/);
  // Verify template is truly unified: difference is only in service names
  const blueLine1 = blue.split('\n')[2];
  const greenLine1 = green.split('\n')[2];
  assert.equal(blueLine1, 'reverse_proxy /api/* api-blue:3002');
  assert.equal(greenLine1, 'reverse_proxy /api/* api-green:3002');
});

test('renderUpstreams throws on invalid color', () => {
  assert.throws(() => renderUpstreams('red'), /Invalid color/);
  assert.throws(() => renderUpstreams('invalid'), /Invalid color/);
});

test('readState returns null for missing file', () => {
  const scratchDir = mkdtempSync(join(tmpdir(), 'bluegreen-test-'));
  try {
    const stateDir = join(scratchDir, 'nonexistent');
    const result = readState(stateDir);
    assert.equal(result, null);
  } finally {
    rmSync(scratchDir, { recursive: true });
  }
});

test('readState returns null with corrupt flag for corrupted state file', () => {
  const scratchDir = mkdtempSync(join(tmpdir(), 'bluegreen-test-'));
  try {
    const stateDir = scratchDir;
    const stateFile = join(stateDir, 'state.json');
    writeFileSync(stateFile, 'not valid json {');
    const result = readState(stateDir);
    assert.equal(result.corrupt, true);
  } finally {
    rmSync(scratchDir, { recursive: true });
  }
});

test('readState tolerates a corrupt state file by reporting, not throwing', () => {
  const scratchDir = mkdtempSync(join(tmpdir(), 'bluegreen-test-'));
  try {
    const stateDir = scratchDir;
    const stateFile = join(stateDir, 'state.json');
    writeFileSync(stateFile, 'garbage garbage garbage');
    const result = readState(stateDir);
    assert.ok(result);
    assert.equal(result.corrupt, true);
  } finally {
    rmSync(scratchDir, { recursive: true });
  }
});

test('writeState and readState round-trip state data', () => {
  const scratchDir = mkdtempSync(join(tmpdir(), 'bluegreen-test-'));
  try {
    const stateDir = scratchDir;
    const state = { activeColor: 'blue', commit: 'abc123', deployedAt: '2026-08-31T12:00:00Z' };
    writeState(stateDir, state);
    const result = readState(stateDir);
    assert.deepEqual(result, state);
  } finally {
    rmSync(scratchDir, { recursive: true });
  }
});

test('writeState atomicity: tmp file fully written before rename, survives rename failure', () => {
  const scratchDir = mkdtempSync(join(tmpdir(), 'bluegreen-test-'));
  try {
    const stateDir = scratchDir;
    const originalState = { activeColor: 'blue', commit: 'abc123', deployedAt: '2026-08-31T12:00:00Z' };

    // Write initial state and capture its bytes
    writeState(stateDir, originalState);
    const stateFile = join(stateDir, 'state.json');
    const beforeBytes = readFileSync(stateFile, 'utf8');

    // Stub renameSync to inject failure and capture call details
    const realRename = fs.renameSync;
    const calls = [];

    try {
      fs.renameSync = (from, to) => {
        // Capture rename call with tmp file content at time of call
        calls.push({
          from,
          to,
          tmpContent: fs.readFileSync(from, 'utf8'),
        });
        throw new Error('injected rename failure');
      };

      const newState = { activeColor: 'green', commit: 'def456', deployedAt: '2026-08-31T13:00:00Z' };

      // Attempt write with stubbed renameSync
      assert.throws(() => writeState(stateDir, newState), /injected rename failure/);

      // Verify rename was called exactly once
      assert.equal(calls.length, 1, 'renameSync must be called exactly once');

      // Verify paths: tmp in same dir as final, both correct
      const tmpFile = join(stateDir, 'state.json.tmp');
      assert.equal(calls[0].from, tmpFile, 'first arg must be tmp file path');
      assert.equal(calls[0].to, stateFile, 'second arg must be final file path');
      assert.equal(dirname(calls[0].from), dirname(calls[0].to), 'tmp and final must be in same directory');

      // Verify tmp file was FULLY written before rename was attempted
      const tmpState = JSON.parse(calls[0].tmpContent);
      assert.deepEqual(tmpState, newState, 'tmp file must contain fully-written new state');

      // Verify original file is UNTOUCHED (rename never happened)
      const afterBytes = readFileSync(stateFile, 'utf8');
      assert.equal(afterBytes, beforeBytes, 'original file must be untouched when rename fails');
    } finally {
      fs.renameSync = realRename;
    }

    // Verify normal write works again after restore
    const finalState = { activeColor: 'purple', commit: 'xyz789', deployedAt: '2026-08-31T14:00:00Z' };
    writeState(stateDir, finalState);
    const result = readState(stateDir);
    assert.deepEqual(result, finalState);
  } finally {
    rmSync(scratchDir, { recursive: true });
  }
});

test('releaseDirFor returns correct path structure', () => {
  const stateDir = 'path/to/state';
  const commit = 'abc123def456';
  const result = releaseDirFor(stateDir, commit);
  assert.match(result, /path[/\\]to[/\\]state[/\\]releases[/\\]abc123def456/);
});

test('prunePlan keeps the 3 newest releases', () => {
  const releases = [
    { commit: 'oldest', mtime: 1000 },
    { commit: 'middle', mtime: 2000 },
    { commit: 'newer', mtime: 3000 },
    { commit: 'newest', mtime: 4000 },
    { commit: 'very-new', mtime: 5000 },
  ];
  const toDelete = prunePlan(releases, 3);
  assert.deepEqual(toDelete.sort(), ['middle', 'oldest']);
  assert.ok(toDelete.includes('oldest'));
  assert.ok(toDelete.includes('middle'));
  assert.ok(!toDelete.includes('newer'));
  assert.ok(!toDelete.includes('newest'));
  assert.ok(!toDelete.includes('very-new'));
});

test('prunePlan never deletes the active commit even if oldest', () => {
  const releases = [
    { commit: 'active-old', mtime: 1000 },
    { commit: 'middle', mtime: 2000 },
    { commit: 'newer', mtime: 3000 },
    { commit: 'newest', mtime: 4000 },
  ];
  const toDelete = prunePlan(releases, 3, 'active-old');
  // Should keep: active-old (explicit), newest, newer (and middle for top 3)
  // Actually: keep 3 newest (newest, newer, middle) PLUS active-old
  assert.ok(!toDelete.includes('active-old'), 'active commit must not be deleted');
});

test('prunePlan respects custom keep count', () => {
  const releases = [
    { commit: 'c1', mtime: 1000 },
    { commit: 'c2', mtime: 2000 },
    { commit: 'c3', mtime: 3000 },
    { commit: 'c4', mtime: 4000 },
    { commit: 'c5', mtime: 5000 },
  ];
  const toDelete = prunePlan(releases, 2);
  assert.deepEqual(toDelete.sort(), ['c1', 'c2', 'c3']);
  assert.ok(!toDelete.includes('c4'));
  assert.ok(!toDelete.includes('c5'));
});

test('prunePlan handles empty releases array', () => {
  const toDelete = prunePlan([]);
  assert.deepEqual(toDelete, []);
});

test('deployStatus returns null for missing status file', () => {
  const scratchDir = mkdtempSync(join(tmpdir(), 'bluegreen-test-'));
  try {
    const stateDir = join(scratchDir, 'nonexistent');
    const result = deployStatus(stateDir);
    assert.equal(result, null);
  } finally {
    rmSync(scratchDir, { recursive: true });
  }
});

test('deployStatus returns null for corrupted status file', () => {
  const scratchDir = mkdtempSync(join(tmpdir(), 'bluegreen-test-'));
  try {
    const stateDir = scratchDir;
    const statusFile = join(stateDir, 'deploy-status.json');
    writeFileSync(statusFile, 'not valid json {');
    const result = deployStatus(stateDir);
    assert.equal(result, null);
  } finally {
    rmSync(scratchDir, { recursive: true });
  }
});

test('writeDeployStatus creates initial status with timestamp and history', () => {
  const scratchDir = mkdtempSync(join(tmpdir(), 'bluegreen-test-'));
  try {
    const stateDir = scratchDir;
    writeDeployStatus(stateDir, 'initializing', 'Started deployment');
    const result = deployStatus(stateDir);
    assert.ok(result);
    assert.equal(result.phase, 'initializing');
    assert.equal(result.detail, 'Started deployment');
    assert.ok(result.timestamp);
    assert.ok(Array.isArray(result.history));
    assert.equal(result.history.length, 1);
    assert.equal(result.history[0].phase, 'initializing');
    assert.equal(result.history[0].detail, 'Started deployment');
  } finally {
    rmSync(scratchDir, { recursive: true });
  }
});

test('writeDeployStatus appends to history and updates current status', () => {
  const scratchDir = mkdtempSync(join(tmpdir(), 'bluegreen-test-'));
  try {
    const stateDir = scratchDir;
    writeDeployStatus(stateDir, 'phase1', 'detail1');
    writeDeployStatus(stateDir, 'phase2', 'detail2');
    const result = deployStatus(stateDir);
    assert.equal(result.phase, 'phase2');
    assert.equal(result.detail, 'detail2');
    assert.equal(result.history.length, 2);
    assert.equal(result.history[0].phase, 'phase1');
    assert.equal(result.history[1].phase, 'phase2');
  } finally {
    rmSync(scratchDir, { recursive: true });
  }
});

test('writeDeployStatus caps history at 50 entries', () => {
  const scratchDir = mkdtempSync(join(tmpdir(), 'bluegreen-test-'));
  try {
    const stateDir = scratchDir;
    // Write 60 entries
    for (let i = 0; i < 60; i++) {
      writeDeployStatus(stateDir, `phase${i}`, `detail${i}`);
    }
    const result = deployStatus(stateDir);
    assert.equal(result.history.length, 50);
    // Should keep the last 50 entries (entries 10-59)
    assert.equal(result.history[0].phase, 'phase10');
    assert.equal(result.history[49].phase, 'phase59');
  } finally {
    rmSync(scratchDir, { recursive: true });
  }
});

test('writeDeployStatus atomicity: tmp file fully written before rename, survives rename failure', () => {
  const scratchDir = mkdtempSync(join(tmpdir(), 'bluegreen-test-'));
  try {
    const stateDir = scratchDir;

    // Write initial status and capture its bytes
    writeDeployStatus(stateDir, 'phase1', 'detail1');
    const statusFile = join(stateDir, 'deploy-status.json');
    const beforeBytes = readFileSync(statusFile, 'utf8');

    // Stub renameSync to inject failure and capture call details
    const realRename = fs.renameSync;
    const calls = [];

    try {
      fs.renameSync = (from, to) => {
        // Capture rename call with tmp file content at time of call
        calls.push({
          from,
          to,
          tmpContent: fs.readFileSync(from, 'utf8'),
        });
        throw new Error('injected rename failure');
      };

      // Attempt write with stubbed renameSync
      assert.throws(() => writeDeployStatus(stateDir, 'phase2', 'detail2'), /injected rename failure/);

      // Verify rename was called exactly once
      assert.equal(calls.length, 1, 'renameSync must be called exactly once');

      // Verify paths: tmp in same dir as final, both correct
      const tmpFile = join(stateDir, 'deploy-status.json.tmp');
      assert.equal(calls[0].from, tmpFile, 'first arg must be tmp file path');
      assert.equal(calls[0].to, statusFile, 'second arg must be final file path');
      assert.equal(dirname(calls[0].from), dirname(calls[0].to), 'tmp and final must be in same directory');

      // Verify tmp file was FULLY written before rename was attempted
      const tmpStatus = JSON.parse(calls[0].tmpContent);
      assert.equal(tmpStatus.phase, 'phase2', 'tmp file must contain new phase');
      assert.equal(tmpStatus.history.length, 2, 'tmp file must have appended history entry');

      // Verify original file is UNTOUCHED (rename never happened)
      const afterBytes = readFileSync(statusFile, 'utf8');
      assert.equal(afterBytes, beforeBytes, 'original file must be untouched when rename fails');
    } finally {
      fs.renameSync = realRename;
    }

    // Verify normal write works again after restore
    writeDeployStatus(stateDir, 'phase3', 'detail3');
    const result = deployStatus(stateDir);
    assert.equal(result.phase, 'phase3');
    assert.equal(result.history.length, 2); // Original phase1 + new phase3
  } finally {
    rmSync(scratchDir, { recursive: true });
  }
});

test('writeDeployStatus includes ISO timestamp in each history entry', () => {
  const scratchDir = mkdtempSync(join(tmpdir(), 'bluegreen-test-'));
  try {
    const stateDir = scratchDir;
    writeDeployStatus(stateDir, 'test', 'detail');
    const result = deployStatus(stateDir);
    const timestamp = result.history[0].timestamp;
    // Should be valid ISO format
    assert.ok(/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}/.test(timestamp));
  } finally {
    rmSync(scratchDir, { recursive: true });
  }
});
