import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import test from 'node:test';
import { GeneratedDeadlineKind } from '@charitypilot/shared';

import type { DeadlineView } from './deadline-contract';
import {
  generationSourceLabel,
  generationSourceReferences,
  isLegacyCompletionDateUnknown,
} from './deadline-contract';
import { deadlineMeta, sortCurrentDeadlines, summarizeDeadlines } from './deadline-display';

function deadline(overrides: Partial<DeadlineView> = {}): DeadlineView {
  return {
    id: 'deadline-1',
    organisationId: 'org-1',
    title: 'Annual report',
    description: null,
    dueDate: '2026-06-30',
    scheduleVersion: 1,
    isAutoGenerated: false,
    generatedKind: null,
    generatedKey: null,
    generationVersion: null,
    generationRuleVersion: null,
    generationFingerprint: null,
    generationSource: null,
    generationInputs: null,
    profileRuleKey: null,
    isComplete: false,
    completedDate: null,
    completionDateKnown: true,
    reminderDays: [30, 14, 7],
    supersededAt: null,
    supersededById: null,
    supersessionReason: null,
    archivedAt: null,
    createdAt: '2026-01-01T00:00:00.000Z',
    updatedAt: '2026-01-01T00:00:00.000Z',
    ...overrides,
  };
}

test('deadline status uses civil days without UTC-midnight drift', () => {
  assert.deepEqual(deadlineMeta(deadline(), '2026-06-30'), {
    daysUntil: 0,
    dueState: 'due-soon',
    badgeLabel: 'Due today',
    priorityLabel: 'Due now',
  });
  assert.equal(deadlineMeta(deadline(), '2026-07-01').badgeLabel, '1 day overdue');
  assert.equal(deadlineMeta(deadline({ dueDate: '2026-06-30T00:00:00.000Z' }), '2026-06-29').daysUntil, 1);
});

test('deadline sorting is canonical and completed records follow current work', () => {
  const sorted = sortCurrentDeadlines([
    deadline({ id: 'complete', dueDate: '2026-01-01', isComplete: true }),
    deadline({ id: 'later', dueDate: '2026-08-31' }),
    deadline({ id: 'earlier', dueDate: '2026-06-30' }),
  ]);
  assert.deepEqual(sorted.map((item) => item.id), ['earlier', 'later', 'complete']);
});

test('summary counts additive generated kinds during the compatibility window', () => {
  assert.deepEqual(
    summarizeDeadlines(
      [
        deadline({ id: 'generated', generatedKind: GeneratedDeadlineKind.CHARITY_ANNUAL_REPORT }),
        deadline({ id: 'overdue', dueDate: '2026-05-01' }),
      ],
      '2026-06-01',
    ),
    { open: 2, overdue: 1, dueSoon: 1, system: 1 },
  );
});

test('generated source labels read the API sources array', () => {
  const item = deadline({
    generationSource: {
      sources: [
        {
          authority: 'Companies Registration Office',
          title: 'Filing an Annual Return',
          url: 'https://cro.ie/annual-return',
          checkedAt: '2026-07-10',
        },
        { authority: 'Law Reform Commission', title: 'Companies Act 2014, section 343' },
      ],
    },
  });
  assert.equal(
    generationSourceLabel(item),
    'Companies Registration Office: Filing an Annual Return; Law Reform Commission: Companies Act 2014, section 343',
  );
  assert.deepEqual(generationSourceReferences(item), [{
    name: 'Companies Registration Office: Filing an Annual Return',
    url: 'https://cro.ie/annual-return',
    lastChecked: '2026-07-10',
  }]);
});

test('legacy completed rows disclose that their completion date was not recorded', () => {
  assert.equal(isLegacyCompletionDateUnknown(deadline({
    isComplete: true,
    completedDate: null,
    completionDateKnown: false,
  })), true);
  assert.equal(isLegacyCompletionDateUnknown(deadline({
    isComplete: true,
    completedDate: '2026-07-10T12:00:00.000Z',
    completionDateKnown: true,
  })), false);

  const panelSource = readFileSync(
    join(process.cwd(), 'src', 'app', '(dashboard)', 'deadlines', 'deadline-history-panel.tsx'),
    'utf8',
  );
  assert.match(panelSource, /Completion date not recorded \(legacy\)/u);
});
