import {
  GeneratedDeadlineKind,
  type DeadlineReminderLogResponse,
  type DeadlineResponse,
} from '@charitypilot/shared';

export type DeadlineView = DeadlineResponse;

export type DeadlineReminderHistoryEntry = DeadlineReminderLogResponse;

export type DeadlinePage<T> = {
  data: T[];
  total: number;
  page: number;
  pageSize: number;
  hasMore: boolean;
};

export const GENERATED_DEADLINE_KIND_LABELS: Record<GeneratedDeadlineKind, string> = {
  [GeneratedDeadlineKind.CHARITY_ANNUAL_REPORT]: 'Charities Regulator annual report',
  [GeneratedDeadlineKind.COMPANY_FINANCIAL_STATEMENTS]: 'Company financial statements',
  [GeneratedDeadlineKind.COMPANY_ANNUAL_MEMBER_ACTION]: 'Company annual member action',
  [GeneratedDeadlineKind.CRO_ANNUAL_RETURN]: 'CRO annual return',
  [GeneratedDeadlineKind.LEGACY_UNVERIFIED]: 'Legacy calculated deadline',
};

export type GeneratedDeadlineSourceReference = {
  name: string;
  url: string;
  lastChecked?: string | null;
};

export function isGeneratedDeadline(deadline: DeadlineView): boolean {
  return Boolean(deadline.isAutoGenerated || deadline.generatedKind || deadline.generatedKey);
}

export function isLegacyCompletionDateUnknown(deadline: DeadlineView): boolean {
  return deadline.isComplete && deadline.completionDateKnown === false;
}

export function generatedDeadlineLabel(deadline: DeadlineView): string {
  if (deadline.generatedKind) return GENERATED_DEADLINE_KIND_LABELS[deadline.generatedKind];
  return deadline.isAutoGenerated ? 'System-generated deadline' : 'Custom deadline';
}

function generationSourceItems(deadline: DeadlineView) {
  const source = deadline.generationSource;
  if (!source || typeof source !== 'object' || !Array.isArray(source.sources)) return [];

  return source.sources.flatMap((item) => {
    if (typeof item === 'string' && item.trim()) {
      return [{ label: item.trim(), url: null, checkedAt: null }];
    }
    if (!item || typeof item !== 'object') return [];
    const record = item as Record<string, unknown>;
    const title = typeof record.title === 'string' ? record.title.trim() : '';
    const authority = typeof record.authority === 'string' ? record.authority.trim() : '';
    const label = title && authority ? `${authority}: ${title}` : title || authority;
    if (!label) return [];
    const url = typeof record.url === 'string' && /^https:\/\//iu.test(record.url.trim())
      ? record.url.trim()
      : null;
    const checkedAt = typeof record.checkedAt === 'string' && record.checkedAt.trim()
      ? record.checkedAt.trim()
      : null;
    return [{ label, url, checkedAt }];
  });
}

export function generationSourceReferences(deadline: DeadlineView): GeneratedDeadlineSourceReference[] {
  return generationSourceItems(deadline).flatMap((item) => item.url ? [{
    name: item.label,
    url: item.url,
    lastChecked: item.checkedAt,
  }] : []);
}

export function generationSourceLabel(deadline: DeadlineView): string | null {
  const source = deadline.generationSource;
  if (!source || typeof source !== 'object') return null;
  const name = source.name;
  if (typeof name === 'string' && name.trim()) return name.trim();

  const labels = generationSourceItems(deadline).map((item) => item.label);

  return labels.length ? labels.join('; ') : null;
}
