import type { DeadlineView } from './deadline-contract';
import {
  civilDaysBetween,
  civilToday,
  compareCivilDates,
  formatCivilDate,
} from './civil-date';

export type DeadlineDueState = 'complete' | 'overdue' | 'due-soon' | 'upcoming';

export type DeadlineMeta = {
  daysUntil: number;
  dueState: DeadlineDueState;
  badgeLabel: string;
  priorityLabel: string;
};

export function deadlineMeta(
  deadline: DeadlineView,
  today = civilToday(),
): DeadlineMeta {
  const daysUntil = civilDaysBetween(today, deadline.dueDate);
  const dayLabel = (value: number) => `${value} day${value === 1 ? '' : 's'}`;
  let dueState: DeadlineDueState = 'upcoming';
  let badgeLabel = Number.isFinite(daysUntil) ? `${dayLabel(daysUntil)} left` : 'Date needs review';
  let priorityLabel = 'Scheduled';

  if (deadline.isComplete) {
    dueState = 'complete';
    badgeLabel = 'Complete';
    priorityLabel = 'Closed';
  } else if (!Number.isFinite(daysUntil)) {
    dueState = 'due-soon';
    priorityLabel = 'Review date';
  } else if (daysUntil < 0) {
    dueState = 'overdue';
    badgeLabel = `${dayLabel(Math.abs(daysUntil))} overdue`;
    priorityLabel = 'Board priority';
  } else if (daysUntil === 0) {
    dueState = 'due-soon';
    badgeLabel = 'Due today';
    priorityLabel = 'Due now';
  } else if (daysUntil <= 30) {
    dueState = 'due-soon';
    badgeLabel = `${dayLabel(daysUntil)} left`;
    priorityLabel = 'Due soon';
  }

  return { daysUntil, dueState, badgeLabel, priorityLabel };
}

export function sortCurrentDeadlines(deadlines: DeadlineView[]): DeadlineView[] {
  return [...deadlines].sort((left, right) => {
    if (left.isComplete !== right.isComplete) return left.isComplete ? 1 : -1;
    return compareCivilDates(left.dueDate, right.dueDate);
  });
}

export function summarizeDeadlines(deadlines: DeadlineView[], today = civilToday()) {
  return deadlines.reduce(
    (summary, deadline) => {
      const meta = deadlineMeta(deadline, today);
      if (!deadline.isComplete) summary.open += 1;
      if (meta.dueState === 'overdue') summary.overdue += 1;
      if (meta.dueState === 'due-soon') summary.dueSoon += 1;
      if (deadline.isAutoGenerated || deadline.generatedKind) summary.system += 1;
      return summary;
    },
    { open: 0, overdue: 0, dueSoon: 0, system: 0 },
  );
}

export { formatCivilDate };
